// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "screens.h"

extern lv_group_t *dac_output_group_main;

static void ui_dac_create_frequency_rollers(lv_obj_t * parent, uint32_t value)
{
    uint32_t divisor = 100000U;
    uint8_t i;

    for(i = 0; i < UI_DAC_FREQUENCY_DIGIT_COUNT; i++)
    {
        ui_DACFrequencyRollers[i] = lv_roller_create(parent);
        lv_roller_set_options(ui_DACFrequencyRollers[i], "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
        lv_roller_set_selected(ui_DACFrequencyRollers[i], (value / divisor) % 10U, LV_ANIM_OFF);
        lv_obj_set_width(ui_DACFrequencyRollers[i], 20);
        lv_obj_set_x(ui_DACFrequencyRollers[i],
                     20 * ((int32_t)i - (int32_t)UI_DAC_FREQUENCY_DIGIT_COUNT + 1) + 50);
        lv_obj_set_y(ui_DACFrequencyRollers[i], -2);
        lv_obj_set_align(ui_DACFrequencyRollers[i], LV_ALIGN_BOTTOM_MID);
        lv_obj_set_style_text_font(ui_DACFrequencyRollers[i], &ui_font_jetbrainsMonoMedium20,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_roller_set_visible_row_count(ui_DACFrequencyRollers[i], 1);
        lv_obj_set_style_text_color(ui_DACFrequencyRollers[i], lv_color_hex(0x000000),
                                    LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_DACFrequencyRollers[i], lv_color_hex(0x000000),
                                    LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_text_opa(ui_DACFrequencyRollers[i], LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_opa(ui_DACFrequencyRollers[i], LV_OPA_COVER, LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_left(ui_DACFrequencyRollers[i], 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_right(ui_DACFrequencyRollers[i], 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_DACFrequencyRollers[i], LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_DACFrequencyRollers[i], 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_DACFrequencyRollers[i], LV_OPA_TRANSP,
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_DACFrequencyRollers[i], lv_color_hex(0x0091E6),
                                  LV_PART_SELECTED | LV_STATE_FOCUS_KEY);
        lv_obj_set_style_bg_opa(ui_DACFrequencyRollers[i], LV_OPA_COVER,
                                LV_PART_SELECTED | LV_STATE_FOCUS_KEY);
        lv_obj_set_style_outline_color(ui_DACFrequencyRollers[i], lv_color_hex(0x000000),
                                       LV_PART_MAIN | LV_STATE_FOCUS_KEY);
        lv_obj_set_style_outline_opa(ui_DACFrequencyRollers[i], LV_OPA_COVER,
                                     LV_PART_MAIN | LV_STATE_FOCUS_KEY);
        lv_obj_set_style_outline_width(ui_DACFrequencyRollers[i], 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
        lv_obj_set_style_outline_pad(ui_DACFrequencyRollers[i], 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
        lv_obj_add_event_cb(ui_DACFrequencyRollers[i], cb_DACFrequencyRollerChanged,
                            LV_EVENT_VALUE_CHANGED, NULL);
        divisor /= 10U;
    }
}

void ui_DACoutput_add_group(void)
{
    uint8_t i;

    lv_group_add_obj(dac_output_group_main, ui_DACWaveRoller);
    for(i = 0; i < UI_DAC_FREQUENCY_DIGIT_COUNT; i++)
    {
        lv_group_add_obj(dac_output_group_main, ui_DACFrequencyRollers[i]);
    }
    lv_group_add_obj(dac_output_group_main, ui_returnDACHomeB);
    lv_group_focus_obj(ui_DACWaveRoller);
}

void ui_DACoutput_screen_init(void)
{
    current_screen_set(SCREEN_DAC_OUTPUT);

    if(dac_output_group_main == NULL)
    {
        dac_output_group_main = lv_group_create();
    }

    ui_DACoutput = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DACoutput, LV_OBJ_FLAG_SCROLLABLE);

    ui_DACtitle = lv_label_create(ui_DACoutput);
    lv_obj_set_width(ui_DACtitle, 240);
    lv_obj_set_height(ui_DACtitle, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_DACtitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DACtitle, "\x44\x41\x43\x20\xE8\xBE\x93\xE5\x87\xBA"); /* 原文：DAC 输出 */
    lv_obj_set_style_text_color(ui_DACtitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DACtitle, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DACtitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DACtitle, &ui_font_PuHuiTi25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DACtitle, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DACtitle, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnDACHomeB = lv_btn_create(ui_DACoutput);
    lv_obj_set_height(ui_returnDACHomeB, 18);
    lv_obj_set_width(ui_returnDACHomeB, lv_pct(96));
    lv_obj_set_y(ui_returnDACHomeB, -4);
    lv_obj_set_align(ui_returnDACHomeB, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_returnDACHomeB, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_returnDACHomeB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_returnDACHomeB, lv_color_hex(0x0073FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnDACHomeB, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_returnDACHomeB, lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_returnDACHomeB, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_returnDACHomeB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_returnDACHomeB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_returnDACHomeL = lv_label_create(ui_returnDACHomeB);
    lv_obj_set_width(ui_returnDACHomeL, lv_pct(100));
    lv_obj_set_height(ui_returnDACHomeL, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_returnDACHomeL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnDACHomeL, "Home");
    lv_obj_set_style_text_align(ui_returnDACHomeL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnDACHomeL, &ui_font_jetbrainsMonoMedium20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DACContainerPanel = lv_obj_create(ui_DACoutput);
    lv_obj_remove_style_all(ui_DACContainerPanel);
    lv_obj_set_height(ui_DACContainerPanel, 175);
    lv_obj_set_width(ui_DACContainerPanel, lv_pct(100));
    lv_obj_set_y(ui_DACContainerPanel, 32);
    lv_obj_set_align(ui_DACContainerPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_DACContainerPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DACContainerPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DACContainerPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    ui_OutputWaveContainer = lv_obj_create(ui_DACContainerPanel);
    lv_obj_remove_style_all(ui_OutputWaveContainer);
    lv_obj_set_height(ui_OutputWaveContainer, 100);
    lv_obj_set_width(ui_OutputWaveContainer, lv_pct(100));
    lv_obj_clear_flag(ui_OutputWaveContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    ui_OutputWaveLabel = lv_label_create(ui_OutputWaveContainer);
    lv_obj_set_width(ui_OutputWaveLabel, lv_pct(80));
    lv_obj_set_height(ui_OutputWaveLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_OutputWaveLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_OutputWaveLabel, "\xE8\xBE\x93\xE5\x87\xBA\xE6\xB3\xA2\xE5\xBD\xA2"); /* 原文：输出波形 */
    lv_obj_set_style_text_align(ui_OutputWaveLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OutputWaveLabel, &ui_font_PuHuiTi25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DACWaveRoller = lv_roller_create(ui_OutputWaveContainer);
    lv_roller_set_options(ui_DACWaveRoller,
                          "\xE6\xAD\xA3\xE5\xBC\xA6\xE6\xB3\xA2\x0A\xE6\x96\xB9\xE6\xB3\xA2\x0A\xE4\xB8\x89\xE8\xA7\x92\xE6\xB3\xA2\x0A\xE6\xA2\xAF\xE5\xBD\xA2\xE6\xB3\xA2\x0A\xE4\xB8\x8A\xE5\x8D\x87\xE6\x96\x9C\xE5\x9D\xA1\xE9\x94\xAF\xE9\xBD\xBF\xE6\xB3\xA2\x0A\xE4\xB8\x8B\xE9\x99\x8D\xE6\x96\x9C\xE5\x9D\xA1\xE9\x94\xAF\xE9\xBD\xBF\xE6\xB3\xA2", /* 原文：正弦波、方波、三角波、梯形波、上升斜坡锯齿波、下降斜坡锯齿波 */
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_DACWaveRoller, lv_pct(90));
    lv_obj_set_align(ui_DACWaveRoller, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_font(ui_DACWaveRoller, &ui_font_PuHuiTi16GB2312, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DACWaveRoller, &ui_font_PuHuiTi16GB2312, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_roller_set_visible_row_count(ui_DACWaveRoller, 2);
    lv_obj_set_style_outline_color(ui_DACWaveRoller, lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_DACWaveRoller, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_DACWaveRoller, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_add_event_cb(ui_DACWaveRoller, cb_DACWaveRollerChanged, LV_EVENT_VALUE_CHANGED, NULL);

    ui_OutputWaveFrequencyContainer = lv_obj_create(ui_DACContainerPanel);
    lv_obj_remove_style_all(ui_OutputWaveFrequencyContainer);
    lv_obj_set_height(ui_OutputWaveFrequencyContainer, 65);
    lv_obj_set_width(ui_OutputWaveFrequencyContainer, lv_pct(100));
    lv_obj_clear_flag(ui_OutputWaveFrequencyContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    ui_OutputWaveFrequencyLabel = lv_label_create(ui_OutputWaveFrequencyContainer);
    lv_obj_set_width(ui_OutputWaveFrequencyLabel, lv_pct(80));
    lv_obj_set_height(ui_OutputWaveFrequencyLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_OutputWaveFrequencyLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_OutputWaveFrequencyLabel, "\xE8\xBE\x93\xE5\x87\xBA\xE9\xA2\x91\xE7\x8E\x87"); /* 原文：输出频率 */
    lv_obj_set_style_text_align(ui_OutputWaveFrequencyLabel, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OutputWaveFrequencyLabel, &ui_font_PuHuiTi25,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dac_create_frequency_rollers(ui_OutputWaveFrequencyContainer, 1000U);

    lv_obj_t * frequency_unit = lv_label_create(ui_OutputWaveFrequencyContainer);
    lv_label_set_text(frequency_unit, "Hz");
    lv_obj_set_x(frequency_unit, 78);
    lv_obj_set_y(frequency_unit, -5);
    lv_obj_set_align(frequency_unit, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_font(frequency_unit, &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_returnDACHomeB, ui_event_returnDACHomeB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DACoutput, ui_event_DACoutput, LV_EVENT_ALL, NULL);

    ui_DACoutput_add_group();
}

void ui_DACoutput_screen_del(void)
{
    lv_obj_del(ui_DACoutput);
    ui_DACoutput = NULL;
}
