// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "lv_file_explorer.h"
#include "screens.h"

#define WINDOW_WIDTH 240
#define WINDOW_HEIGHT 240
#define TITLE_HEIGHT 25
#define TITLE_WIDTH 240

//参考文件：https://github.com/RT-Thread-Studio/sdk-bsp-stm32f407-spark/blob/main/projects/06_demo_factory/applications/lvgl/UIDemo/Page/Page_SDCard.c

char current_path[LV_FILE_EXPLORER_PATH_MAX_LEN];
const char * root_path = "S:";

lv_obj_t* list1;
static lv_style_t style;
lv_obj_t* file_explorer_panel;

extern lv_group_t *file_explorer_group;
extern lv_indev_t *indev;

void file_explorerevent_handler(lv_event_t * e);


// static void file_explorer_event_cb(lv_event_t* e)
// {
// 	const char* s = lv_file_explorer_get_selected_file_name(file_explorer_panel);
// 	const char* dir = lv_file_explorer_get_current_path(file_explorer_panel);
// 	LOG_I("%s",s);
// 	LOG_I("%s",dir);
// 	LV_LOG_USER("Clicked: Msg Close %s\n", s);
// //	if(is_avi_file(s))
// //	{
// //		sprintf(file_name,"%s%s",dir,s);
// //		//PM_Push(Page, PAGE_VideoPlayer);
// //	}
// }
static bool is_end_with(const char * str1, const char * str2)
{
    if(str1 == NULL || str2 == NULL)
        return false;

    uint16_t len1 = strlen(str1);
    uint16_t len2 = strlen(str2);
    if((len1 < len2) || (len1 == 0 || len2 == 0))
        return false;

    while(len2 >= 1) {
        if(str2[len2 - 1] != str1[len1 - 1])
            return false;

        len2--;
        len1--;
    }

    return true;
}

static void strip_ext(char * dir)
{
    char * end = dir + strlen(dir);

    while(end >= dir && *end != '/') {
        --end;
    }

    if(end > dir) {
        *end = '\0';
    }
    else if(end == dir) {
        *(end + 1) = '\0';
    }
}

static const char* get_file_symbol(const char* filename) {
    // 返回基于文件扩展名的符号，或者NULL表示跳过
    if (is_end_with(filename, ".png") || is_end_with(filename, ".PNG") ||
        is_end_with(filename, ".jpg") || is_end_with(filename, ".JPG") ||
        is_end_with(filename, ".bmp") || is_end_with(filename, ".BMP") ||
        is_end_with(filename, ".gif") || is_end_with(filename, ".GIF")) {
        return LV_SYMBOL_IMAGE;
    }
    else if (is_end_with(filename, ".mp3") || is_end_with(filename, ".MP3")) {
        return LV_SYMBOL_AUDIO;
    }
    else if (is_end_with(filename, ".mp4") || is_end_with(filename, ".MP4") ||
             is_end_with(filename, ".avi") || is_end_with(filename, ".AVI")) {
        return LV_SYMBOL_VIDEO;
    }
    else if (filename[0] == '/') {
        return LV_SYMBOL_DIRECTORY;
    }
    else if (!is_end_with(filename, ".") && !is_end_with(filename, "..")) {
        return LV_SYMBOL_FILE;
    }
    return NULL;
}

#define MAX_FILES_VISIBLE 20  // 最大显示文件数量

static void showDir(const char* path) {
    char fn[LV_FILE_EXPLORER_PATH_MAX_LEN];
    uint16_t file_count = 0;
    lv_fs_dir_t dir;
    lv_fs_res_t res;
    lv_obj_t* obj = list1;
    lv_obj_t* btn;

    lv_obj_clean(obj);  // 清空现有列表

    // 创建表示当前路径和上一层路径的按钮
    //    btn = lv_list_add_btn(obj, LV_SYMBOL_DIRECTORY, ".");
    //    lv_obj_add_style(btn, &style, LV_PART_MAIN);
    //    lv_obj_set_style_bg_color(btn, lv_color_make(0, 0x40, 0xDD), LV_PART_MAIN | LV_STATE_FOCUSED);
    //    lv_group_add_obj(file_explorer_group, btn);
    //    lv_obj_add_event_cb(btn,file_explorerevent_handler,LV_EVENT_CLICKED, NULL);

    btn = lv_list_add_btn(obj, LV_SYMBOL_DIRECTORY, "..");
    lv_obj_add_style(btn, &style, LV_PART_MAIN);
    lv_obj_set_style_bg_color(btn, lv_color_make(0, 0x40, 0xDD), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_group_add_obj(file_explorer_group, btn);
    lv_obj_add_event_cb(btn,file_explorerevent_handler,LV_EVENT_CLICKED, NULL);

    res = lv_fs_dir_open(&dir, path);
    if (res != LV_FS_RES_OK) {
        LV_LOG_ERROR("Open dir error %d!", res);
        btn = lv_list_add_btn(obj, LV_SYMBOL_WARNING, "Open dir error !");
        lv_obj_add_style(btn, &style, LV_PART_MAIN);
        lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);

        if(res == LV_FS_RES_HW_ERR)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "Low level hardware error");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_FS_ERR)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "Error in the file system structure");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_NOT_EX)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "Driver, file or directory is not exists");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_FULL)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "Disk full");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_LOCKED)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "The file is already opened");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_DENIED)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "Access denied. Check 'fs_open' modes and write protect");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_BUSY)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "The file system now can't handle it, try later");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_TOUT)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "Process time outed");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_NOT_IMP)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "Requested function is not implemented");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_OUT_OF_MEM)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "Not enough memory for an internal operation");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_INV_PARAM)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "Invalid parameter among arguments");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        else if (res == LV_FS_RES_UNKNOWN)
        {
            btn = lv_list_add_btn(obj, LV_SYMBOL_BELL, "Other unknown error");
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_RED), 0);
        }
        return;
    }

    // 读取目录项并添加到列表，直到达到文件数量限制
    while (file_count < MAX_FILES_VISIBLE) {
        res = lv_fs_dir_read(&dir, fn);
        if (res != LV_FS_RES_OK) {
            LV_LOG_ERROR("Read dir error %d!", res);
            break;
        }
        if (fn[0] == '\0') {
            break;
        }

        // 根据文件类型选择符号
        const char * symbol = get_file_symbol(fn);

        if (symbol) {
            btn = lv_list_add_btn(obj, symbol, fn);
            lv_obj_add_style(btn, &style, LV_PART_MAIN);
            lv_obj_set_style_bg_color(btn, lv_color_make(0, 0x40, 0xDD), LV_PART_MAIN | LV_STATE_FOCUSED);
            lv_group_add_obj(file_explorer_group, btn);
            lv_obj_add_event_cb(btn,file_explorerevent_handler,LV_EVENT_CLICKED, NULL);

            lv_obj_t* label = lv_obj_get_child(btn, 1);
            lv_label_set_long_mode(label, LV_LABEL_LONG_WRAP);

            file_count++;
        }
    }

    lv_fs_dir_close(&dir);
    lv_event_send(obj, LV_EVENT_READY, NULL);
    lv_obj_scroll_to_y(obj, 0, LV_ANIM_OFF);
    lv_snprintf(current_path, sizeof(current_path), "%s", path);
}

extern uint8_t current_path_return;
extern char choose_device_path[LV_FILE_EXPLORER_PATH_MAX_LEN];
extern char choose_firmware_bin_path[LV_FILE_EXPLORER_PATH_MAX_LEN];

void ui_FileExplorer_screen_del(void);

void file_explorerevent_handler(lv_event_t *e)
{
    const char *str_fn = NULL;
    char file_name[LV_FILE_EXPLORER_PATH_MAX_LEN];
    lv_obj_t *obj = lv_group_get_focused(file_explorer_group);
    str_fn = lv_list_get_btn_text(list1, obj);
    LV_LOG_TRACE("selected entry: %s", str_fn);
    if ((strcmp(str_fn, ".") == 0))
        return;

    if (strcmp(str_fn, "..") == 0 && strlen(current_path) <= 3)
    {
        if (current_path_return == 3)
        {
            current_screen_set(SCREEN_MENU);
            _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Menu_screen_init);
        }
        return;
    }

    if ((strcmp(str_fn, "..") == 0) && (strlen(current_path) > 3))
    {
        strip_ext(current_path);
        /*Remove the last '/' character*/
        strip_ext(current_path);
        lv_snprintf((char *)file_name, sizeof(file_name), "%s", current_path);
    }
    else
    {
       if (strcmp(str_fn, "..") != 0)
       {
          lv_snprintf((char *)file_name, sizeof(file_name), "%s%s",
                      current_path, str_fn);
       }
    }

    lv_fs_dir_t dir;
    LV_LOG_TRACE("open path: %s", file_name);
    if (lv_fs_dir_open(&dir, file_name) == LV_FS_RES_OK)
    {
        lv_fs_dir_close(&dir);
        showDir(file_name);
    }
    else
    {
		lv_snprintf((char *)file_name, sizeof(file_name), "%s/%s",current_path, str_fn);
        if (current_path_return == 1)
        {
            current_path_return = 0;
            lv_snprintf(current_path, sizeof(current_path), "%s", file_name);
            rt_strncpy(choose_device_path, rt_strstr(current_path, "/"),
                       sizeof(current_path) - 2);
            lv_label_set_text(ui_currentDevicePath, choose_device_path);
            current_screen_set(SCREEN_OFFLINE_DOWNLOAD);
            lv_disp_load_scr(ui_OfflineDownload);
            return;
        }
        else if (current_path_return == 2)
        {
            current_path_return = 0;
            lv_snprintf(current_path, sizeof(current_path), "%s", file_name);
            rt_strncpy(choose_firmware_bin_path,
                       rt_strstr(current_path, "/"),
                       sizeof(current_path) - 2);
            lv_label_set_text(ui_currentBinPath, choose_firmware_bin_path);
            current_screen_set(SCREEN_OFFLINE_DOWNLOAD);
            lv_disp_load_scr(ui_OfflineDownload);
            return;
        }
    }
}

static void List_Create(lv_obj_t* par)
{
//	File_Explorer_Create(par);

    lv_style_init(&style);
    lv_style_set_bg_color(&style, lv_color_make(0xFF, 0xFF, 0xFF));
    lv_style_set_radius(&style, 5);
    lv_style_set_border_color(&style, lv_color_make(0xFF, 0xFF, 0xFF));
    lv_style_set_text_color(&style, lv_color_make(0x00, 0x00, 0x00));
    lv_style_set_pad_all(&style, 5);
	lv_style_set_text_font(&style, &ui_font_PuHuiTi16GB2312);
	
    lv_obj_t* obj = lv_list_create(par);
	lv_obj_add_style(obj, &style, LV_PART_MAIN);
    lv_obj_set_size(obj, WINDOW_WIDTH, WINDOW_HEIGHT-TITLE_HEIGHT);
    lv_obj_set_align(obj, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(obj, 0, LV_PART_MAIN);
    lv_obj_add_flag(obj, LV_OBJ_FLAG_EVENT_BUBBLE);//Propagate the events to the parent too
	
	list1 = obj;

	showDir(root_path);

//    lv_memset_00(explorer->current_path, sizeof(explorer->current_path));
//    strcpy(explorer->current_path, path);
//    lv_label_set_text_fmt(Title, LV_SYMBOL_EYE_OPEN" %s", path);

//    size_t current_path_len = strlen(explorer->current_path);
//    if((*((explorer->current_path) + current_path_len) != '/') && (current_path_len < LV_FILE_EXPLORER_PATH_MAX_LEN)) {
//        *((explorer->current_path) + current_path_len) = '/';
//    }
}

// static void File_Explorer_Create(lv_obj_t *par)
// {
//
//     file_explorer_panel = lv_file_explorer_create(par);
//     //lv_obj_set_style_border_width(file_explorer_panel, 5, LV_PART_MAIN);
//     lv_obj_set_size(file_explorer_panel, WINDOW_WIDTH, WINDOW_HEIGHT-TITLE_HEIGHT);
//     lv_obj_align(file_explorer_panel, LV_ALIGN_CENTER, 0, 0);
//
//     lv_file_explorer_set_sort(file_explorer_panel, LV_EXPLORER_SORT_NONE);
//     lv_file_explorer_open_dir(file_explorer_panel, "S:/");
//
//     lv_obj_add_event_cb(file_explorer_panel, file_explorer_event_cb, LV_EVENT_VALUE_CHANGED, par);
// }

void ui_FileExplorer_screen_init(void)
{
    current_screen_set(SCREEN_FILE_EXPLORER);

	if(file_explorer_group == NULL)
	{
	file_explorer_group = lv_group_create();
	lv_group_set_editing(file_explorer_group, false);   //导航模式
	}
	
    ui_FileExplorer = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FileExplorer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_FileExplorer, ui_event_FileExplorer, LV_EVENT_ALL, NULL);

    ui_FileExplorerTitle = lv_label_create(ui_FileExplorer);
    lv_obj_set_width(ui_FileExplorerTitle, 240);
    lv_obj_set_height(ui_FileExplorerTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FileExplorerTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_FileExplorerTitle, "文件浏览器");
    lv_obj_set_style_text_color(ui_FileExplorerTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FileExplorerTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_FileExplorerTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FileExplorerTitle, &ui_font_PuHuiTi25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FileExplorerTitle, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FileExplorerTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    List_Create(ui_FileExplorer);
	
	
    // File_Explorer_Create(ui_FileExplorer);
}

void ui_FileExplorer_screen_del(void)
{
    lv_obj_del(ui_FileExplorer);
	ui_FileExplorer = NULL;
}
