// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "screens.h"

void ui_Menu_screen_init(void)
{
    current_screen_set(SCREEN_MENU);

    ui_Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menuPanel = lv_obj_create(ui_Menu);
    lv_obj_set_width(ui_menuPanel, lv_pct(100));
    lv_obj_set_height(ui_menuPanel, lv_pct(71));
    lv_obj_set_x(ui_menuPanel, 0);
    lv_obj_set_y(ui_menuPanel, 29);
    lv_obj_set_align(ui_menuPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menuPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_menuPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_menuPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_menuPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuDAPLINKB = lv_btn_create(ui_menuPanel);
    lv_obj_set_height(ui_menuDAPLINKB, 40);
    lv_obj_set_width(ui_menuDAPLINKB, lv_pct(100));
    lv_obj_set_align(ui_menuDAPLINKB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuDAPLINKB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menuDAPLINKB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_menuDAPLINKB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuDAPLINKB, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_menuDAPLINKB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_menuDAPLINKB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menuDAPLINKB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menuDAPLINKB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_menuDAPLINKB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_menuDAPLINKB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_menuDAPLINKB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menuDAPLINKB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_color(ui_menuDAPLINKB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_menuDAPLINKB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menuDAPLINKL = lv_label_create(ui_menuDAPLINKB);
    lv_obj_set_width(ui_menuDAPLINKL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuDAPLINKL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menuDAPLINKL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuDAPLINKL, "在线DAPLINK");

    ui_menuOfflineB = lv_btn_create(ui_menuPanel);
    lv_obj_set_height(ui_menuOfflineB, 40);
    lv_obj_set_width(ui_menuOfflineB, lv_pct(100));
    lv_obj_set_align(ui_menuOfflineB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuOfflineB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menuOfflineB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_menuOfflineB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuOfflineB, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_menuOfflineB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_menuOfflineB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menuOfflineB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menuOfflineB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_menuOfflineB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_menuOfflineB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_menuOfflineB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menuOfflineB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_color(ui_menuOfflineB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_menuOfflineB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menuOfflineL = lv_label_create(ui_menuOfflineB);
    lv_obj_set_width(ui_menuOfflineL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuOfflineL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menuOfflineL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuOfflineL, "脱机烧录器");

    ui_menuAmmeterB = lv_btn_create(ui_menuPanel);
    lv_obj_set_height(ui_menuAmmeterB, 40);
    lv_obj_set_width(ui_menuAmmeterB, lv_pct(100));
    lv_obj_set_align(ui_menuAmmeterB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuAmmeterB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menuAmmeterB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_menuAmmeterB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuAmmeterB, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_menuAmmeterB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_menuAmmeterB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menuAmmeterB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menuAmmeterB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_menuAmmeterB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_menuAmmeterB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_menuAmmeterB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menuAmmeterB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_color(ui_menuAmmeterB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_menuAmmeterB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menuAmmeterL = lv_label_create(ui_menuAmmeterB);
    lv_obj_set_width(ui_menuAmmeterL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuAmmeterL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menuAmmeterL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuAmmeterL, "电压电流输出");

    ui_menuUARTB = lv_btn_create(ui_menuPanel);
    lv_obj_set_height(ui_menuUARTB, 40);
    lv_obj_set_width(ui_menuUARTB, lv_pct(100));
    lv_obj_set_align(ui_menuUARTB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuUARTB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menuUARTB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_menuUARTB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuUARTB, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_menuUARTB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_menuUARTB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menuUARTB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menuUARTB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_menuUARTB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_menuUARTB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_menuUARTB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menuUARTB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_color(ui_menuUARTB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_menuUARTB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menuUARTL = lv_label_create(ui_menuUARTB);
    lv_obj_set_width(ui_menuUARTL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuUARTL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menuUARTL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuUARTL, "串口监视器");

    ui_menuPWMB = lv_btn_create(ui_menuPanel);
    lv_obj_set_height(ui_menuPWMB, 40);
    lv_obj_set_width(ui_menuPWMB, lv_pct(100));
    lv_obj_set_align(ui_menuPWMB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuPWMB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menuPWMB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_menuPWMB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuPWMB, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_menuPWMB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_menuPWMB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menuPWMB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menuPWMB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_menuPWMB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_menuPWMB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_menuPWMB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menuPWMB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_color(ui_menuPWMB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_menuPWMB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menuPWML = lv_label_create(ui_menuPWMB);
    lv_obj_set_width(ui_menuPWML, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuPWML, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menuPWML, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuPWML, "PWM输出");

    ui_menuDACOutputB = lv_btn_create(ui_menuPanel);
    lv_obj_set_height(ui_menuDACOutputB, 40);
    lv_obj_set_width(ui_menuDACOutputB, lv_pct(100));
    lv_obj_set_align(ui_menuDACOutputB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuDACOutputB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menuDACOutputB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_menuDACOutputB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuDACOutputB, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_menuDACOutputB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_menuDACOutputB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menuDACOutputB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menuDACOutputB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_menuDACOutputB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_menuDACOutputB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_menuDACOutputB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menuDACOutputB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_color(ui_menuDACOutputB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_menuDACOutputB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menuDACOutputL = lv_label_create(ui_menuDACOutputB);
    lv_obj_set_width(ui_menuDACOutputL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuDACOutputL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menuDACOutputL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuDACOutputL, "DAC输出");

    ui_menuSDCardB = lv_btn_create(ui_menuPanel);
    lv_obj_set_height(ui_menuSDCardB, 40);
    lv_obj_set_width(ui_menuSDCardB, lv_pct(100));
    lv_obj_set_align(ui_menuSDCardB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuSDCardB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menuSDCardB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_menuSDCardB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuSDCardB, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_menuSDCardB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_menuSDCardB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menuSDCardB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menuSDCardB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_menuSDCardB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_menuSDCardB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_menuSDCardB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menuSDCardB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_color(ui_menuSDCardB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_menuSDCardB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menuSDCardL = lv_label_create(ui_menuSDCardB);
    lv_obj_set_width(ui_menuSDCardL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuSDCardL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menuSDCardL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuSDCardL, "文件浏览器");

    ui_logoAndTextContainer2 = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_logoAndTextContainer2);
    lv_obj_set_height(ui_logoAndTextContainer2, 57);
    lv_obj_set_width(ui_logoAndTextContainer2, lv_pct(98));
    lv_obj_set_x(ui_logoAndTextContainer2, 0);
    lv_obj_set_y(ui_logoAndTextContainer2, 5);
    lv_obj_set_align(ui_logoAndTextContainer2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_logoAndTextContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoLite2 = lv_img_create(ui_logoAndTextContainer2);
    lv_img_set_src(ui_LogoLite2, &ui_img_743788411);
    lv_obj_set_width(ui_LogoLite2, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_LogoLite2, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_align(ui_LogoLite2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_LogoLite2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoLite2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoTitle2 = lv_label_create(ui_logoAndTextContainer2);
    lv_obj_set_width(ui_LogoTitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoTitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoTitle2, -4);
    lv_obj_set_y(ui_LogoTitle2, 0);
    lv_obj_set_align(ui_LogoTitle2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LogoTitle2, "立创开发板");
    lv_obj_set_style_text_color(ui_LogoTitle2, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LogoTitle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LogoTitle2, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoWebsite2 = lv_label_create(ui_logoAndTextContainer2);
    lv_obj_set_width(ui_LogoWebsite2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoWebsite2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoWebsite2, -13);
    lv_obj_set_y(ui_LogoWebsite2, -2);
    lv_obj_set_align(ui_LogoWebsite2, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_LogoWebsite2, "WWW.LCKFB.COM");
    lv_obj_set_style_text_color(ui_LogoWebsite2, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LogoWebsite2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LogoWebsite2, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuAboutB = lv_btn_create(ui_menuPanel);
    lv_obj_set_height(ui_menuAboutB, 40);
    lv_obj_set_width(ui_menuAboutB, lv_pct(100));
    lv_obj_set_align(ui_menuAboutB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuAboutB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menuAboutB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_menuAboutB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuAboutB, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_menuAboutB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_menuAboutB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menuAboutB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menuAboutB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_menuAboutB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_menuAboutB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_menuAboutB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menuAboutB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_color(ui_menuAboutB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_menuAboutB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menuAboutL = lv_label_create(ui_menuAboutB);
    lv_obj_set_width(ui_menuAboutL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuAboutL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menuAboutL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuAboutL, "关于");

    lv_obj_add_event_cb(ui_menuDAPLINKB, ui_event_menuDAPLINKB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuOfflineB, ui_event_menuOfflineB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuAmmeterB, ui_event_menuAmmeterB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuUARTB, ui_event_menuUARTB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuPWMB, ui_event_menuPWMB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuDACOutputB, ui_event_menuDACOutputB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuSDCardB, ui_event_menuSDCardB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuAboutB, ui_event_menuAboutB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Menu, ui_event_Menu, LV_EVENT_ALL, NULL);
}
