// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "screens.h"

extern lv_group_t *offline_download_group;

void ui_OfflineDownload_add_group(void)
{
    lv_group_add_obj(offline_download_group, ui_chooseDeviceB);
    lv_group_add_obj(offline_download_group, ui_chooseBinB);
    lv_group_add_obj(offline_download_group, ui_startOfflineDownloadB);
//    lv_group_add_obj(offline_download_group, ui_downloadConfigureB);
    lv_group_add_obj(offline_download_group, ui_ODreturnHome);

    lv_group_set_editing(offline_download_group, false);   //导航模式

}


void ui_OfflineDownload_screen_init(void)
{
    current_screen_set(SCREEN_OFFLINE_DOWNLOAD);

    if(offline_download_group == NULL)
    {
        offline_download_group = lv_group_create();
        lv_group_set_editing(offline_download_group, false);   //导航模式
    }

    ui_OfflineDownload = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OfflineDownload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OfflineDownloadTitle = lv_label_create(ui_OfflineDownload);
    lv_obj_set_width(ui_OfflineDownloadTitle, 240);
    lv_obj_set_height(ui_OfflineDownloadTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OfflineDownloadTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_OfflineDownloadTitle, "脱机烧录器");
    lv_obj_set_style_text_color(ui_OfflineDownloadTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OfflineDownloadTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_OfflineDownloadTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OfflineDownloadTitle, &ui_font_PuHuiTi25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OfflineDownloadTitle, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OfflineDownloadTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfflineDownloadContainer = lv_obj_create(ui_OfflineDownload);
    lv_obj_remove_style_all(ui_OfflineDownloadContainer);
    lv_obj_set_height(ui_OfflineDownloadContainer, 190);
    lv_obj_set_width(ui_OfflineDownloadContainer, lv_pct(100));
    lv_obj_set_x(ui_OfflineDownloadContainer, 0);
    lv_obj_set_y(ui_OfflineDownloadContainer, -20);
    lv_obj_set_align(ui_OfflineDownloadContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_OfflineDownloadContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OfflineDownloadProcessBar = lv_bar_create(ui_OfflineDownloadContainer);
    lv_obj_set_height(ui_OfflineDownloadProcessBar, 20);
    lv_obj_set_width(ui_OfflineDownloadProcessBar, lv_pct(96));
    lv_obj_set_x(ui_OfflineDownloadProcessBar, 0);
    lv_obj_set_y(ui_OfflineDownloadProcessBar, -3);
    lv_obj_set_align(ui_OfflineDownloadProcessBar, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_OfflineDownloadProcessBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_OfflineDownloadProcessBar, lv_color_hex(0x777171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_OfflineDownloadProcessBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_OfflineDownloadProcessBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_OfflineDownloadProcessBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_OfflineDownloadProcessBar, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_OfflineDownloadProcessBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_OfflineDownloadProcessNum = lv_label_create(ui_OfflineDownloadProcessBar);
    lv_obj_set_width(ui_OfflineDownloadProcessNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OfflineDownloadProcessNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OfflineDownloadProcessNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfflineDownloadProcessNum, "0%");
    lv_obj_set_style_text_color(ui_OfflineDownloadProcessNum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OfflineDownloadProcessNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_OfflineDownloadProcessNum, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OfflineDownloadProcessNum, &ui_font_jetbrainsMonoMedium16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offlineDownloadButtonContainer = lv_obj_create(ui_OfflineDownloadContainer);
    lv_obj_remove_style_all(ui_offlineDownloadButtonContainer);
    lv_obj_set_width(ui_offlineDownloadButtonContainer, 85);
    lv_obj_set_height(ui_offlineDownloadButtonContainer, 165);
    lv_obj_set_x(ui_offlineDownloadButtonContainer, 3);
    lv_obj_set_y(ui_offlineDownloadButtonContainer, -1);
    lv_obj_set_flex_flow(ui_offlineDownloadButtonContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_offlineDownloadButtonContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_offlineDownloadButtonContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chooseDeviceB = lv_btn_create(ui_offlineDownloadButtonContainer);
    lv_obj_set_width(ui_chooseDeviceB, 80);
    lv_obj_set_height(ui_chooseDeviceB, 50);
    lv_obj_set_align(ui_chooseDeviceB, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_chooseDeviceB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_chooseDeviceB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_chooseDeviceB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_chooseDeviceB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_chooseDeviceB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_chooseDeviceB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_chooseDeviceB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_chooseDeviceB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_chooseDeviceB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_chooseDeviceB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_chooseDeviceL = lv_label_create(ui_chooseDeviceB);
    lv_obj_set_width(ui_chooseDeviceL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chooseDeviceL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_chooseDeviceL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chooseDeviceL, "芯片型号");
    lv_obj_set_style_text_font(ui_chooseDeviceL, &ui_font_PuhuiTi20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chooseBinB = lv_btn_create(ui_offlineDownloadButtonContainer);
    lv_obj_set_width(ui_chooseBinB, 80);
    lv_obj_set_height(ui_chooseBinB, 50);
    lv_obj_set_x(ui_chooseBinB, 2);
    lv_obj_set_y(ui_chooseBinB, 41);
    lv_obj_set_align(ui_chooseBinB, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_chooseBinB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_chooseBinB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_chooseBinB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_chooseBinB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_chooseBinB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_chooseBinB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_chooseBinB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_chooseBinB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_chooseBinB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_chooseBinB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_chooseBinL = lv_label_create(ui_chooseBinB);
    lv_obj_set_width(ui_chooseBinL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chooseBinL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_chooseBinL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chooseBinL, "选择固件");
    lv_obj_set_style_text_font(ui_chooseBinL, &ui_font_PuhuiTi20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startOfflineDownloadB = lv_btn_create(ui_offlineDownloadButtonContainer);
    lv_obj_set_width(ui_startOfflineDownloadB, 80);
    lv_obj_set_height(ui_startOfflineDownloadB, 50);
    lv_obj_set_x(ui_startOfflineDownloadB, 6);
    lv_obj_set_y(ui_startOfflineDownloadB, -34);
    lv_obj_set_align(ui_startOfflineDownloadB, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_startOfflineDownloadB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_startOfflineDownloadB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_startOfflineDownloadB, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startOfflineDownloadB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_startOfflineDownloadB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_startOfflineDownloadB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_startOfflineDownloadB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_startOfflineDownloadB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_startOfflineDownloadB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_startOfflineDownloadB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_startOfflineDownloadB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_startOfflineDownloadB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_startOfflineDownloadL = lv_label_create(ui_startOfflineDownloadB);
    lv_obj_set_width(ui_startOfflineDownloadL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startOfflineDownloadL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_startOfflineDownloadL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startOfflineDownloadL, "开始烧录");
    lv_obj_set_style_text_font(ui_startOfflineDownloadL, &ui_font_PuhuiTi20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_downloadConfigureB = lv_btn_create(ui_offlineDownloadButtonContainer);
    lv_obj_set_width(ui_downloadConfigureB, 80);
    lv_obj_set_height(ui_downloadConfigureB, 20);
    lv_obj_set_x(ui_downloadConfigureB, 92);
    lv_obj_set_y(ui_downloadConfigureB, -32);
    lv_obj_set_align(ui_downloadConfigureB, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_downloadConfigureB, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_downloadConfigureB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_downloadConfigureB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_downloadConfigureB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_downloadConfigureB, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_downloadConfigureB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_downloadConfigureB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_downloadConfigureB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_downloadConfigureB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_downloadConfigureB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_downloadConfigureL = lv_label_create(ui_downloadConfigureB);
    lv_obj_set_width(ui_downloadConfigureL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_downloadConfigureL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_downloadConfigureL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_downloadConfigureL, "烧录参数");
    lv_obj_set_style_text_font(ui_downloadConfigureL, &ui_font_PuhuiTi20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentDevicePath = lv_label_create(ui_OfflineDownloadContainer);
    lv_obj_set_width(ui_currentDevicePath, 140);
    lv_obj_set_height(ui_currentDevicePath, 50);
    lv_obj_set_x(ui_currentDevicePath, 90);
    lv_obj_set_y(ui_currentDevicePath, 0);
    lv_label_set_text(ui_currentDevicePath, "");
    lv_obj_set_style_text_font(ui_currentDevicePath, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_currentDevicePath, lv_color_hex(0x978484), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_currentDevicePath, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_currentDevicePath, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_currentDevicePath, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentBinPath = lv_label_create(ui_OfflineDownloadContainer);
    lv_obj_set_width(ui_currentBinPath, 140);
    lv_obj_set_height(ui_currentBinPath, 50);
    lv_obj_set_x(ui_currentBinPath, 90);
    lv_obj_set_y(ui_currentBinPath, -14);
    lv_obj_set_align(ui_currentBinPath, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_currentBinPath, "");
    lv_obj_set_style_text_font(ui_currentBinPath, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_currentBinPath, lv_color_hex(0x978484), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_currentBinPath, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_currentBinPath, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_currentBinPath, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offlineDownloadInfoContainer = lv_obj_create(ui_OfflineDownloadContainer);
    lv_obj_remove_style_all(ui_offlineDownloadInfoContainer);
    lv_obj_set_width(ui_offlineDownloadInfoContainer, 140);
    lv_obj_set_height(ui_offlineDownloadInfoContainer, 50);
    lv_obj_set_x(ui_offlineDownloadInfoContainer, -10);
    lv_obj_set_y(ui_offlineDownloadInfoContainer, -29);
    lv_obj_set_align(ui_offlineDownloadInfoContainer, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_offlineDownloadInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ODdownloadSuccessCountT = lv_label_create(ui_offlineDownloadInfoContainer);
    lv_obj_set_width(ui_ODdownloadSuccessCountT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ODdownloadSuccessCountT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ODdownloadSuccessCountT, 0);
    lv_obj_set_y(ui_ODdownloadSuccessCountT, 5);
    lv_label_set_text(ui_ODdownloadSuccessCountT, "成功计数:");
    lv_obj_set_style_text_font(ui_ODdownloadSuccessCountT, &ui_font_PuhuiTi20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ODdownloadSuccessCount = lv_label_create(ui_offlineDownloadInfoContainer);
    lv_obj_set_width(ui_ODdownloadSuccessCount, lv_pct(48));
    lv_obj_set_height(ui_ODdownloadSuccessCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ODdownloadSuccessCount, 0);
    lv_obj_set_y(ui_ODdownloadSuccessCount, 2);
    lv_obj_set_align(ui_ODdownloadSuccessCount, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_ODdownloadSuccessCount, "0");
    lv_obj_set_style_text_font(ui_ODdownloadSuccessCount, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ODdownloadSuccessCount, lv_color_hex(0x837D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ODdownloadSuccessCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ODdownloadSuccessCount, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ODdownloadInfo = lv_label_create(ui_offlineDownloadInfoContainer);
    lv_obj_set_width(ui_ODdownloadInfo, lv_pct(100));
    lv_obj_set_height(ui_ODdownloadInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ODdownloadInfo, 0);
    lv_obj_set_y(ui_ODdownloadInfo, -2);
    lv_obj_set_align(ui_ODdownloadInfo, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_ODdownloadInfo, "download info");
    lv_obj_set_style_text_align(ui_ODdownloadInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ODdownloadInfo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ODreturnHome = lv_btn_create(ui_OfflineDownload);
    lv_obj_set_height(ui_ODreturnHome, 18);
    lv_obj_set_width(ui_ODreturnHome, lv_pct(98));
    lv_obj_set_x(ui_ODreturnHome, 0);
    lv_obj_set_y(ui_ODreturnHome, -2);
    lv_obj_set_align(ui_ODreturnHome, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ODreturnHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ODreturnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ODreturnHome, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ODreturnHome, lv_color_hex(0x0073FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ODreturnHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ODreturnHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_ODreturnHome, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_ODreturnHome, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_ODreturnHome, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_ODreturnHomeL = lv_label_create(ui_ODreturnHome);
    lv_obj_set_width(ui_ODreturnHomeL, lv_pct(100));
    lv_obj_set_height(ui_ODreturnHomeL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ODreturnHomeL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ODreturnHomeL, "Home");
    lv_label_set_recolor(ui_ODreturnHomeL, "true");
    lv_obj_set_style_text_align(ui_ODreturnHomeL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ODreturnHomeL, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_chooseDeviceB, ui_event_chooseDeviceB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chooseBinB, ui_event_chooseBinB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_startOfflineDownloadB, ui_event_startOfflineDownloadB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ODreturnHome, ui_event_ODreturnHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OfflineDownload, ui_event_OfflineDownload, LV_EVENT_ALL, NULL);

    ui_OfflineDownload_add_group();
}

void ui_OFFLINE_DOWNLOAD_screen_del(void)
{
    lv_obj_del(ui_OfflineDownload);
    ui_OfflineDownload = NULL;
}
