// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "screens.h"


extern lv_group_t *pwm_output_group_main;

static void ui_pwm_create_rollers(lv_obj_t * parent, lv_obj_t ** rollers, uint32_t value)
{
    uint32_t divisor = 100000U;
    uint8_t i;

    for(i = 0; i < UI_PWM_DIGIT_COUNT; i++)
    {
        rollers[i] = lv_roller_create(parent);
        lv_roller_set_options(rollers[i], "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
        lv_roller_set_visible_row_count(rollers[i], 1);
        lv_roller_set_selected(rollers[i], (value / divisor) % 10U, LV_ANIM_OFF);
        lv_obj_set_width(rollers[i], 20);
        lv_obj_set_x(rollers[i], 20 * ((int32_t)i - (int32_t)UI_PWM_DIGIT_COUNT + 1));
        lv_obj_set_align(rollers[i], LV_ALIGN_RIGHT_MID);
        lv_obj_set_style_text_font(rollers[i], &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(rollers[i], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(rollers[i], lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_text_opa(rollers[i], LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_opa(rollers[i], LV_OPA_COVER, LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_left(rollers[i], 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_right(rollers[i], 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(rollers[i], LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(rollers[i], 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(rollers[i], LV_OPA_TRANSP, LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(rollers[i], lv_color_hex(0x0091E6), LV_PART_SELECTED | LV_STATE_FOCUS_KEY);
        lv_obj_set_style_bg_opa(rollers[i], LV_OPA_COVER, LV_PART_SELECTED | LV_STATE_FOCUS_KEY);
        lv_obj_set_style_outline_color(rollers[i], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
        lv_obj_set_style_outline_opa(rollers[i], 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
        lv_obj_set_style_outline_width(rollers[i], 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
        lv_obj_set_style_outline_pad(rollers[i], 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
        lv_obj_add_event_cb(rollers[i], cb_PWMRollerValueChanged, LV_EVENT_VALUE_CHANGED, NULL);
        divisor /= 10U;
    }
}

void ui_PWMoutput_add_group(void)
{
    uint8_t i;

    for(i = 0; i < UI_PWM_DIGIT_COUNT; i++)
    {
        lv_group_add_obj(pwm_output_group_main, ui_PWMPeriodRollers[i]);
    }
    for(i = 0; i < UI_PWM_DIGIT_COUNT; i++)
    {
        lv_group_add_obj(pwm_output_group_main, ui_PWMPulseRollers[i]);
    }
    lv_group_add_obj(pwm_output_group_main, ui_returnPWMHomeB);
    lv_group_focus_obj(ui_PWMPeriodRollers[0]);
}

void ui_PWMoutput_screen_init(void)
{
    current_screen_set(SCREEN_PWM_OUTPUT);

    if(pwm_output_group_main == NULL)
    {
        pwm_output_group_main = lv_group_create();
        lv_group_set_editing(pwm_output_group_main, false);   //导航模式
    }
    ui_PWMoutput = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PWMoutput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PWMtitle = lv_label_create(ui_PWMoutput);
    lv_obj_set_width(ui_PWMtitle, 240);
    lv_obj_set_height(ui_PWMtitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PWMtitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_PWMtitle, "PWM 输出");
    lv_obj_set_style_text_color(ui_PWMtitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PWMtitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PWMtitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PWMtitle, &ui_font_PuHuiTi25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PWMtitle, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PWMtitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnPWMHomeB = lv_btn_create(ui_PWMoutput);
    lv_obj_set_height(ui_returnPWMHomeB, 18);
    lv_obj_set_width(ui_returnPWMHomeB, lv_pct(96));
    lv_obj_set_x(ui_returnPWMHomeB, 0);
    lv_obj_set_y(ui_returnPWMHomeB, -4);
    lv_obj_set_align(ui_returnPWMHomeB, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_returnPWMHomeB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_returnPWMHomeB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_returnPWMHomeB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_returnPWMHomeB, lv_color_hex(0x0073FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnPWMHomeB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_returnPWMHomeB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_returnPWMHomeB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_returnPWMHomeB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_returnPWMHomeB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_returnPWMHomeL = lv_label_create(ui_returnPWMHomeB);
    lv_obj_set_width(ui_returnPWMHomeL, lv_pct(100));
    lv_obj_set_height(ui_returnPWMHomeL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_returnPWMHomeL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnPWMHomeL, "Home");
    lv_label_set_recolor(ui_returnPWMHomeL, "true");
    lv_obj_set_style_text_align(ui_returnPWMHomeL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnPWMHomeL, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWMContainer = lv_obj_create(ui_PWMoutput);
    lv_obj_remove_style_all(ui_PWMContainer);
    lv_obj_set_height(ui_PWMContainer, 190);
    lv_obj_set_width(ui_PWMContainer, lv_pct(100));
    lv_obj_set_x(ui_PWMContainer, 0);
    lv_obj_set_y(ui_PWMContainer, -20);
    lv_obj_set_align(ui_PWMContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PWMContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PeriodContainer = lv_obj_create(ui_PWMContainer);
    lv_obj_remove_style_all(ui_PeriodContainer);
    lv_obj_set_height(ui_PeriodContainer, 50);
    lv_obj_set_width(ui_PeriodContainer, lv_pct(90));
    lv_obj_set_align(ui_PeriodContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PeriodContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_PeriodContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PeriodContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PeriodContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PeriodContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PeriodLabel = lv_label_create(ui_PeriodContainer);
    lv_obj_set_width(ui_PeriodLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PeriodLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PeriodLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PeriodLabel, "Period\n(ns)");
    lv_obj_set_style_text_align(ui_PeriodLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PeriodLabel, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pwm_create_rollers(ui_PeriodContainer, ui_PWMPeriodRollers, 1000U);

    ui_PulseContainer = lv_obj_create(ui_PWMContainer);
    lv_obj_remove_style_all(ui_PulseContainer);
    lv_obj_set_height(ui_PulseContainer, 50);
    lv_obj_set_width(ui_PulseContainer, lv_pct(90));
    lv_obj_set_x(ui_PulseContainer, 0);
    lv_obj_set_y(ui_PulseContainer, -23);
    lv_obj_set_align(ui_PulseContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PulseContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PulseLabel = lv_label_create(ui_PulseContainer);
    lv_obj_set_width(ui_PulseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PulseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PulseLabel, 3);
    lv_obj_set_y(ui_PulseLabel, 0);
    lv_obj_set_align(ui_PulseLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PulseLabel, "Pulse\n(ns)");
    lv_obj_set_style_text_align(ui_PulseLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PulseLabel, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pwm_create_rollers(ui_PulseContainer, ui_PWMPulseRollers, 500U);

    ui_pwmInfoContainer = lv_obj_create(ui_PWMContainer);
    lv_obj_remove_style_all(ui_pwmInfoContainer);
    lv_obj_set_height(ui_pwmInfoContainer, 60);
    lv_obj_set_width(ui_pwmInfoContainer, lv_pct(95));
    lv_obj_set_x(ui_pwmInfoContainer, -240);
    lv_obj_set_y(ui_pwmInfoContainer, -20);
    lv_obj_set_align(ui_pwmInfoContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_pwmInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PWMfrequencyLabelInfo = lv_label_create(ui_pwmInfoContainer);
    lv_obj_set_width(ui_PWMfrequencyLabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWMfrequencyLabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_PWMfrequencyLabelInfo, "频率值:");
    lv_obj_set_style_text_font(ui_PWMfrequencyLabelInfo, &ui_font_PuHuiTi25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWMDutyCyclelabelInfo = lv_label_create(ui_pwmInfoContainer);
    lv_obj_set_width(ui_PWMDutyCyclelabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWMDutyCyclelabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWMDutyCyclelabelInfo, 0);
    lv_obj_set_y(ui_PWMDutyCyclelabelInfo, -4);
    lv_obj_set_align(ui_PWMDutyCyclelabelInfo, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_PWMDutyCyclelabelInfo, "占空比:");
    lv_obj_set_style_text_font(ui_PWMDutyCyclelabelInfo, &ui_font_PuHuiTi25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWMfrequencyLabel = lv_label_create(ui_pwmInfoContainer);
    lv_obj_set_width(ui_PWMfrequencyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWMfrequencyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWMfrequencyLabel, 100);
    lv_obj_set_y(ui_PWMfrequencyLabel, 0);
    lv_label_set_text(ui_PWMfrequencyLabel, "1.0Mhz");
    lv_obj_set_style_text_font(ui_PWMfrequencyLabel, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWMDutyCyclelabel = lv_label_create(ui_pwmInfoContainer);
    lv_obj_set_width(ui_PWMDutyCyclelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWMDutyCyclelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWMDutyCyclelabel, 100);
    lv_obj_set_y(ui_PWMDutyCyclelabel, -4);
    lv_obj_set_align(ui_PWMDutyCyclelabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_PWMDutyCyclelabel, "0.00000%");
    lv_obj_set_style_text_font(ui_PWMDutyCyclelabel, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_returnPWMHomeB, ui_event_returnPWMHomeB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PWMoutput, ui_event_PWMoutput, LV_EVENT_ALL, NULL);

	ui_PWMoutput_add_group();
}

void ui_PWMoutput_screen_del(void)
{
    lv_obj_del(ui_PWMoutput);
    ui_PWMoutput = NULL;
}
