// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "screens.h"

extern lv_group_t *uart_monitor_group_main;

void ui_UartMonitor_add_group(void)
{
    lv_group_set_editing(uart_monitor_group_main, false);   //导航模式

    lv_group_add_obj(uart_monitor_group_main, ui_UartMonitorBaud);
    lv_group_add_obj(uart_monitor_group_main, ui_UartMonitorParity);
    lv_group_add_obj(uart_monitor_group_main, ui_UMTextArea);
    lv_group_add_obj(uart_monitor_group_main, ui_UMreturnHomeB);
}

void ui_UartMonitor_screen_init(void)
{
    current_screen_set(SCREEN_UART_MONITOR);

    if(uart_monitor_group_main == NULL)
    {
        uart_monitor_group_main = lv_group_create();
        lv_group_set_editing(uart_monitor_group_main, false);   //导航模式
    }

    ui_UartMonitor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_UartMonitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UMreturnHomeB = lv_btn_create(ui_UartMonitor);
    lv_obj_set_height(ui_UMreturnHomeB, 18);
    lv_obj_set_width(ui_UMreturnHomeB, lv_pct(98));
    lv_obj_set_x(ui_UMreturnHomeB, 0);
    lv_obj_set_y(ui_UMreturnHomeB, -2);
    lv_obj_set_align(ui_UMreturnHomeB, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_UMreturnHomeB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UMreturnHomeB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_UMreturnHomeB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UMreturnHomeB, lv_color_hex(0x0073FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UMreturnHomeB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_UMreturnHomeB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_UMreturnHomeB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_UMreturnHomeB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_UMreturnHomeB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_UMreturnHomeL = lv_label_create(ui_UMreturnHomeB);
    lv_obj_set_width(ui_UMreturnHomeL, lv_pct(100));
    lv_obj_set_height(ui_UMreturnHomeL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UMreturnHomeL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UMreturnHomeL, "Home");
    lv_label_set_recolor(ui_UMreturnHomeL, "true");
    lv_obj_set_style_text_align(ui_UMreturnHomeL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UMreturnHomeL, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UartMonitorTitle = lv_label_create(ui_UartMonitor);
    lv_obj_set_width(ui_UartMonitorTitle, 240);
    lv_obj_set_height(ui_UartMonitorTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UartMonitorTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_UartMonitorTitle, "\x28\xE4\xB8\xB2\xE5\x8F\xA3\x29\x54\x54\x4C\x2F\x32\x33\x32\x2F\x34\x38\x35"); /* 原文：(串口)TTL/232/485 */
    lv_obj_set_style_text_color(ui_UartMonitorTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UartMonitorTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_UartMonitorTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UartMonitorTitle, &ui_font_PuHuiTi25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UartMonitorTitle, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UartMonitorTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UartMonitorContainer = lv_obj_create(ui_UartMonitor);
    lv_obj_remove_style_all(ui_UartMonitorContainer);
    lv_obj_set_height(ui_UartMonitorContainer, 190);
    lv_obj_set_width(ui_UartMonitorContainer, lv_pct(100));
    lv_obj_set_x(ui_UartMonitorContainer, 0);
    lv_obj_set_y(ui_UartMonitorContainer, -20);
    lv_obj_set_align(ui_UartMonitorContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_UartMonitorContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UartMonitorBaud = lv_dropdown_create(ui_UartMonitorContainer);
    lv_dropdown_set_options(ui_UartMonitorBaud,
                            "1200\n2400\n4800\n9600\n19200\n38400\n57600\n74800\n115200\n230400\n460800\n500000\n576000\n921600\n1M\n1.5M\n2M");
    lv_obj_set_width(ui_UartMonitorBaud, lv_pct(50));
    lv_obj_set_height(ui_UartMonitorBaud, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UartMonitorBaud, 5);
    lv_obj_set_y(ui_UartMonitorBaud, 2);
    lv_obj_add_flag(ui_UartMonitorBaud, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_outline_color(ui_UartMonitorBaud, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_UartMonitorBaud, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_UartMonitorBaud, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_UartMonitorBaud, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);



    ui_UartMonitorParity = lv_dropdown_create(ui_UartMonitorContainer);
    lv_dropdown_set_options(ui_UartMonitorParity, "NONE\nENEN\nODD");
    lv_obj_set_width(ui_UartMonitorParity, lv_pct(40));
    lv_obj_set_height(ui_UartMonitorParity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UartMonitorParity, -5);
    lv_obj_set_y(ui_UartMonitorParity, 2);
    lv_obj_set_align(ui_UartMonitorParity, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_UartMonitorParity, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_outline_color(ui_UartMonitorParity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_UartMonitorParity, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_UartMonitorParity, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_UartMonitorParity, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);



    ui_UMTextAreaContainer = lv_obj_create(ui_UartMonitorContainer);
    lv_obj_remove_style_all(ui_UMTextAreaContainer);
    lv_obj_set_height(ui_UMTextAreaContainer, 145);
    lv_obj_set_width(ui_UMTextAreaContainer, lv_pct(95));
    lv_obj_set_x(ui_UMTextAreaContainer, 0);
    lv_obj_set_y(ui_UMTextAreaContainer, -5);
    lv_obj_set_align(ui_UMTextAreaContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_UMTextAreaContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_UMTextAreaContainer, &ui_font_PuHuiTi16GB2312,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UMTextArea = lv_textarea_create(ui_UMTextAreaContainer);
    lv_obj_set_width(ui_UMTextArea, lv_pct(100));
    lv_obj_set_height(ui_UMTextArea, lv_pct(100));
    lv_obj_set_align(ui_UMTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_UMTextArea, 512);
    lv_textarea_set_placeholder_text(ui_UMTextArea, "wait fo uart data");
    lv_obj_set_style_radius(ui_UMTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UMTextArea, lv_color_hex(0xD4FC79), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UMTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_UMTextArea, lv_color_hex(0x96E6A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_UMTextArea, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_UMTextArea, lv_color_hex(0xD1C2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_UMTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_UMTextArea, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_UMreturnHomeB, ui_event_UMreturnHomeB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UartMonitorBaud, ui_event_UartMonitorBaud, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UartMonitorParity, ui_event_UartMonitorParity, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UartMonitor, ui_event_UartMonitor, LV_EVENT_ALL, NULL);

    ui_UartMonitor_add_group();
}


void ui_UartMonitor_screen_del(void)
{
    lv_obj_del(ui_UartMonitor);
    ui_UartMonitor = NULL;
}
