// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void ZOOM_LOGO_Animation(lv_obj_t * TargetObject, int delay);
void SHOW_SLOGAN_Animation(lv_obj_t * TargetObject, int delay);
void Title_Down_Animation(lv_obj_t * TargetObject, int delay);
void DAPLINK_HOME_UP_Animation(lv_obj_t * TargetObject, int delay);
void pwmKeyboardup_Animation(lv_obj_t * TargetObject, int delay);
void pwmKeyboarddown_Animation(lv_obj_t * TargetObject, int delay);
void pwmInfoLeftToShow_Animation(lv_obj_t * TargetObject, int delay);
void pwmInfoShowToRight_Animation(lv_obj_t * TargetObject, int delay);
void ZOOM_LCSC_Animation(lv_obj_t * TargetObject, int delay);
void LOGO_TITLE_DOWN_Animation(lv_obj_t * TargetObject, int delay);
void LOGO_WEBSITE_LEFT_Animation(lv_obj_t * TargetObject, int delay);
void DAC_KEYBOARD_UP_Animation(lv_obj_t * TargetObject, int delay);
void DAC_KEYBOARD_DOWN_Animation(lv_obj_t * TargetObject, int delay);
void DAC_PANEL_UP_Animation(lv_obj_t * TargetObject, int delay);
void DAC_PANEL_DOWN_Animation(lv_obj_t * TargetObject, int delay);
void ENLARGE_MENU_OBJ_Animation(lv_obj_t * TargetObject, int delay);
void DISLARGE_MENU_OBJ_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_INIT
void ui_INIT_screen_init(void);
void ui_event_INIT(lv_event_t * e);
lv_obj_t * ui_INIT;
lv_obj_t * ui_infoTitle;
lv_obj_t * ui_slogan;
lv_obj_t * ui_logoAndTextContainer;
lv_obj_t * ui_LogoLite;
lv_obj_t * ui_LogoTitle;
lv_obj_t * ui_LogoWebsite;


// SCREEN: ui_Menu
void ui_Menu_screen_init(void);
void ui_event_Menu(lv_event_t * e);
lv_obj_t * ui_Menu;
lv_obj_t * ui_menuPanel;
void ui_event_menuDAPLINKB(lv_event_t * e);
lv_obj_t * ui_menuDAPLINKB;
lv_obj_t * ui_menuDAPLINKL;
void ui_event_menuOfflineB(lv_event_t * e);
lv_obj_t * ui_menuOfflineB;
lv_obj_t * ui_menuOfflineL;
void ui_event_menuAmmeterB(lv_event_t * e);
lv_obj_t * ui_menuAmmeterB;
lv_obj_t * ui_menuAmmeterL;
void ui_event_menuUARTB(lv_event_t * e);
lv_obj_t * ui_menuUARTB;
lv_obj_t * ui_menuUARTL;
void ui_event_menuPWMB(lv_event_t * e);
lv_obj_t * ui_menuPWMB;
lv_obj_t * ui_menuPWML;
void ui_event_menuDACOutputB(lv_event_t * e);
lv_obj_t * ui_menuDACOutputB;
lv_obj_t * ui_menuDACOutputL;
void ui_event_menuSDCardB(lv_event_t * e);
lv_obj_t * ui_menuSDCardB;
lv_obj_t * ui_menuSDCardL;
lv_obj_t * ui_logoAndTextContainer2;
lv_obj_t * ui_LogoLite2;
lv_obj_t * ui_LogoTitle2;
lv_obj_t * ui_LogoWebsite2;
void ui_event_menuAboutB(lv_event_t * e);
lv_obj_t * ui_menuAboutB;
lv_obj_t * ui_menuAboutL;

// SCREEN: ui_DAPLINK
void ui_DAPLINK_screen_init(void);
void ui_event_DAPLINK(lv_event_t * e);
lv_obj_t * ui_DAPLINK;
lv_obj_t * ui_title;
lv_obj_t * ui_DBG;
lv_obj_t * ui_dbgModeB;
lv_obj_t * ui_dbgModeL;
lv_obj_t * ui_dbgClockB;
lv_obj_t * ui_dbgClockL;
lv_obj_t * ui_dbgIDCODEB;
lv_obj_t * ui_dbgIDCODEL;
lv_obj_t * ui_uartInfoB;
lv_obj_t * ui_uartInfoL;
lv_obj_t * ui_PowerPanel;
void ui_event_Power5V0CheckBox(lv_event_t * e);
lv_obj_t * ui_Power5V0CheckBox;
void ui_event_Power3V3CheckBox(lv_event_t * e);
lv_obj_t * ui_Power3V3CheckBox;
lv_obj_t * ui_POWER5VMeasure;
lv_obj_t * ui_POWER3VMeasure;
lv_obj_t * ui_POWER3CMeasure;
lv_obj_t * ui_POWER5CMeasure;
void ui_event_returnHomeB(lv_event_t * e);
lv_obj_t * ui_returnHomeB;
lv_obj_t * ui_returnHomeL;
lv_obj_t * ui_PDPanel;
void ui_event_PDControlRoller(lv_event_t * e);
lv_obj_t * ui_PDControlRoller;
lv_obj_t * ui_POWERPDVmeasure;
lv_obj_t * ui_POWERPDImeasure;
void ui_event_PDOutputEN(lv_event_t * e);
lv_obj_t * ui_PDOutputEN;


// SCREEN: ui_FileExplorer
void ui_FileExplorer_screen_init(void);
void ui_event_FileExplorer(lv_event_t * e);
lv_obj_t * ui_FileExplorer;
lv_obj_t * ui_FileExplorerTitle;


// SCREEN: ui_OfflineDownload
void ui_OfflineDownload_screen_init(void);
void ui_event_OfflineDownload(lv_event_t * e);
lv_obj_t * ui_OfflineDownload;
lv_obj_t * ui_OfflineDownloadTitle;
lv_obj_t * ui_OfflineDownloadContainer;
lv_obj_t * ui_OfflineDownloadProcessBar;
lv_obj_t * ui_OfflineDownloadProcessNum;
lv_obj_t * ui_offlineDownloadButtonContainer;
void ui_event_chooseDeviceB(lv_event_t * e);
lv_obj_t * ui_chooseDeviceB;
lv_obj_t * ui_chooseDeviceL;
void ui_event_chooseBinB(lv_event_t * e);
lv_obj_t * ui_chooseBinB;
lv_obj_t * ui_chooseBinL;
void ui_event_startOfflineDownloadB(lv_event_t * e);
lv_obj_t * ui_startOfflineDownloadB;
lv_obj_t * ui_startOfflineDownloadL;
lv_obj_t * ui_downloadConfigureB;
lv_obj_t * ui_downloadConfigureL;
lv_obj_t * ui_currentDevicePath;
lv_obj_t * ui_currentBinPath;
lv_obj_t * ui_offlineDownloadInfoContainer;
lv_obj_t * ui_ODdownloadSuccessCountT;
lv_obj_t * ui_ODdownloadSuccessCount;
lv_obj_t * ui_ODdownloadInfo;
void ui_event_ODreturnHome(lv_event_t * e);
lv_obj_t * ui_ODreturnHome;
lv_obj_t * ui_ODreturnHomeL;


// SCREEN: ui_VoltAmmeter
void ui_VoltAmmeter_screen_init(void);
void ui_event_VoltAmmeter(lv_event_t * e);
lv_obj_t * ui_VoltAmmeter;
lv_obj_t * ui_VoltAmmeterTitle;
lv_obj_t * ui_VoltAmmeterContainer;
void ui_event_VATabview(lv_event_t * e);
lv_obj_t * ui_VATabview;
lv_obj_t * ui_TabPage5V0;
lv_obj_t * ui_MPOWER5VMeasureB;
lv_obj_t * ui_MPOWER5VMeasureL;
lv_obj_t * ui_MPOWER5IMeasureB;
lv_obj_t * ui_MPOWER5IMeasureL;
lv_obj_t * ui_MPOWER5PMeasureB2;
lv_obj_t * ui_MPOWER5PMeasureL;
lv_obj_t * ui_TabPage3V3;
lv_obj_t * ui_MPOWER3VMeasureB;
lv_obj_t * ui_MPOWER3VMeasureL;
lv_obj_t * ui_MPOWER3IMeasureB;
lv_obj_t * ui_MPOWER3IMeasureL;
lv_obj_t * ui_MPOWER3PMeasureB;
lv_obj_t * ui_MPOWER3PMeasureL;
lv_obj_t * ui_TabPagePD;
lv_obj_t * ui_MPOWERPDVMeasureB;
lv_obj_t * ui_MPOWERPDVMeasureL;
lv_obj_t * ui_MPOWERPDIMeasureB;
lv_obj_t * ui_MPOWERPDIMeasureL;
lv_obj_t * ui_MPOWERPDPMeasureB;
lv_obj_t * ui_MPOWERPDPMeasureL;
lv_obj_t * ui_TabPageSet;
void ui_event_VAOUTPUT5V0ENABLEB(lv_event_t * e);
lv_obj_t * ui_VAOUTPUT5V0ENABLEB;
lv_obj_t * ui_VAOUTPUT5V0ENABLEL;
void ui_event_VAOUTPUT3V3ENABLEB(lv_event_t * e);
lv_obj_t * ui_VAOUTPUT3V3ENABLEB;
lv_obj_t * ui_VAOUTPUT3V3ENABLEL;
void ui_event_VAOUTPUTPDENABLEB(lv_event_t * e);
lv_obj_t * ui_VAOUTPUTPDENABLEB;
lv_obj_t * ui_VAOUTPUTPDENABLEL;
lv_obj_t * ui_VAPDSinkControl;
void ui_event_VAPDOPTIONDropDown(lv_event_t * e);
lv_obj_t * ui_VAPDOPTIONDropDown;
lv_obj_t * ui_PDSinkState;
void ui_event_VAreturnHomeB(lv_event_t * e);
lv_obj_t * ui_VAreturnHomeB;
lv_obj_t * ui_VAreturnHomeL;


// SCREEN: ui_UartMonitor
void ui_UartMonitor_screen_init(void);
void ui_event_UartMonitor(lv_event_t * e);
lv_obj_t * ui_UartMonitor;
void ui_event_UMreturnHomeB(lv_event_t * e);
lv_obj_t * ui_UMreturnHomeB;
lv_obj_t * ui_UMreturnHomeL;
lv_obj_t * ui_UartMonitorTitle;
lv_obj_t * ui_UartMonitorContainer;
void ui_event_UartMonitorBaud(lv_event_t * e);
lv_obj_t * ui_UartMonitorBaud;
void ui_event_UartMonitorParity(lv_event_t * e);
lv_obj_t * ui_UartMonitorParity;
lv_obj_t * ui_UMTextAreaContainer;
lv_obj_t * ui_UMTextArea;


// SCREEN: ui_PWMoutput
void ui_PWMoutput_screen_init(void);
void ui_event_PWMoutput(lv_event_t * e);
lv_obj_t * ui_PWMoutput;
lv_obj_t * ui_PWMtitle;
void ui_event_returnPWMHomeB(lv_event_t * e);
lv_obj_t * ui_returnPWMHomeB;
lv_obj_t * ui_returnPWMHomeL;
lv_obj_t * ui_PWMContainer;
lv_obj_t * ui_PeriodContainer;
lv_obj_t * ui_PeriodLabel;
void ui_event_TextAreaPeriod(lv_event_t * e);
lv_obj_t * ui_TextAreaPeriod;
lv_obj_t * ui_PulseContainer;
lv_obj_t * ui_PulseLabel;
void ui_event_TextAreaPulse(lv_event_t * e);
lv_obj_t * ui_TextAreaPulse;
lv_obj_t * ui_pwmKeyboardContainer;
void ui_event_PWMKeyboard(lv_event_t * e);
lv_obj_t * ui_PWMKeyboard;
lv_obj_t * ui_pwmInfoContainer;
lv_obj_t * ui_PWMfrequencyLabelInfo;
lv_obj_t * ui_PWMDutyCyclelabelInfo;
lv_obj_t * ui_PWMfrequencyLabel;
lv_obj_t * ui_PWMDutyCyclelabel;


// SCREEN: ui_DACoutput
void ui_DACoutput_screen_init(void);
void ui_event_DACoutput(lv_event_t * e);
lv_obj_t * ui_DACoutput;
lv_obj_t * ui_DACtitle;
void ui_event_returnDACHomeB(lv_event_t * e);
lv_obj_t * ui_returnDACHomeB;
lv_obj_t * ui_returnDACHomeL;
lv_obj_t * ui_DACContainer;
void ui_event_KeyboardDAC(lv_event_t * e);
lv_obj_t * ui_KeyboardDAC;
lv_obj_t * ui_DACContainerPanel;
lv_obj_t * ui_OutputWaveContainer;
lv_obj_t * ui_OutputWaveLabel;
void ui_event_OutputWaveDP(lv_event_t * e);
lv_obj_t * ui_OutputWaveDP;
lv_obj_t * ui_OutputWaveFrequencyContainer;
lv_obj_t * ui_OutputWaveFrequencyLabel;
void ui_event_TextAreaWaveFrequencyVoltage(lv_event_t * e);
lv_obj_t * ui_TextAreaWaveFrequencyVoltage;
lv_obj_t * ui_OutputVoltageContainer;
lv_obj_t * ui_OutputVoltageLabel;
void ui_event_TextAreaDACVoltage(lv_event_t * e);
lv_obj_t * ui_TextAreaDACVoltage;
lv_obj_t * ui_OutputSelfWaveContainer;
lv_obj_t * ui_OutputSelfWaveLabel;
void ui_event_DACSelfWave(lv_event_t * e);
lv_obj_t * ui_DACSelfWave;
lv_obj_t * ui____initial_actions0;


// SCREEN: ui_About
void ui_About_screen_init(void);
lv_obj_t * ui_About;
lv_obj_t * ui_Abouttitle;
lv_obj_t * ui_AboutHomeB;
lv_obj_t * ui_AboutHomeL;
lv_obj_t * ui_AboutContainerPanel;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void ZOOM_LOGO_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_0, -100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom);
    lv_anim_start(&PropertyAnimation_0);

}
void SHOW_SLOGAN_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 130, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}
void Title_Down_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -50, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void DAPLINK_HOME_UP_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 20, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}
void pwmKeyboardup_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 106, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void pwmKeyboarddown_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, 106);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void pwmInfoLeftToShow_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -240, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void pwmInfoShowToRight_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 240);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void ZOOM_LCSC_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_0, 0, 256);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void LOGO_TITLE_DOWN_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -50, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void LOGO_WEBSITE_LEFT_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 200, -13);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void DAC_KEYBOARD_UP_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 60, -26);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void DAC_KEYBOARD_DOWN_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -26, 60);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void DAC_PANEL_UP_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_height);
    lv_anim_set_values(&PropertyAnimation_0, 190, 135);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void DAC_PANEL_DOWN_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_height);
    lv_anim_set_values(&PropertyAnimation_0, 135, 190);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void ENLARGE_MENU_OBJ_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_height);
    lv_anim_set_values(&PropertyAnimation_0, 40, 50);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void DISLARGE_MENU_OBJ_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_height);
    lv_anim_set_values(&PropertyAnimation_0, 50, 40);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_INIT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 300, 1300, &ui_Menu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        SHOW_SLOGAN_Animation(ui_slogan, 0);
        ZOOM_LCSC_Animation(ui_LogoLite, 0);
        LOGO_TITLE_DOWN_Animation(ui_LogoTitle, 0);
        LOGO_WEBSITE_LEFT_Animation(ui_LogoWebsite, 0);
    }
}
void ui_event_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        cb_loadedMenu(e);
    }
}
void ui_event_menuDAPLINKB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DAPLINK, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_DAPLINK_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        cb_clicked_menu_to_daplink(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ENLARGE_MENU_OBJ_Animation(ui_menuDAPLINKB, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        DISLARGE_MENU_OBJ_Animation(ui_menuDAPLINKB, 0);
    }
}
void ui_event_menuOfflineB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OfflineDownload, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_OfflineDownload_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        cb_clicked_menu_to_offline_download(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ENLARGE_MENU_OBJ_Animation(ui_menuOfflineB, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        DISLARGE_MENU_OBJ_Animation(ui_menuOfflineB, 0);
    }
}
void ui_event_menuAmmeterB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_VoltAmmeter, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_VoltAmmeter_screen_init);
        cb_screenToVoltAmmeter(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ENLARGE_MENU_OBJ_Animation(ui_menuAmmeterB, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        DISLARGE_MENU_OBJ_Animation(ui_menuAmmeterB, 0);
    }
}
void ui_event_menuUARTB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_UartMonitor, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_UartMonitor_screen_init);
        cb_screenToUartMonitor(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ENLARGE_MENU_OBJ_Animation(ui_menuUARTB, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        DISLARGE_MENU_OBJ_Animation(ui_menuUARTB, 0);
    }
}
void ui_event_menuPWMB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PWMoutput, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_PWMoutput_screen_init);
        cb_menutoPWMscreen(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ENLARGE_MENU_OBJ_Animation(ui_menuPWMB, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        DISLARGE_MENU_OBJ_Animation(ui_menuPWMB, 0);
    }
}
void ui_event_menuDACOutputB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DACoutput, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_DACoutput_screen_init);
        cb_menutoDACscreen(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ENLARGE_MENU_OBJ_Animation(ui_menuDACOutputB, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        DISLARGE_MENU_OBJ_Animation(ui_menuDACOutputB, 0);
    }
}
void ui_event_menuSDCardB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FileExplorer, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_FileExplorer_screen_init);
        cb_clicked_menu_to_file_explorer(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ENLARGE_MENU_OBJ_Animation(ui_menuSDCardB, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        DISLARGE_MENU_OBJ_Animation(ui_menuSDCardB, 0);
    }
}
void ui_event_menuAboutB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_About, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_About_screen_init);
        cb_menutoAboutscreen(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ENLARGE_MENU_OBJ_Animation(ui_menuAboutB, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        DISLARGE_MENU_OBJ_Animation(ui_menuAboutB, 0);
    }
}
void ui_event_DAPLINK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Title_Down_Animation(ui_title, 200);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        DAPLINK_HOME_UP_Animation(ui_returnHomeB, 200);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        cb_DAPLINKScreenLoad(e);
    }
}
void ui_event_Power5V0CheckBox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_daplinkPower5V0cCheckBoxValueChange(e);
    }
}
void ui_event_Power3V3CheckBox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_daplinkPower3V3cCheckBoxValueChange(e);
    }
}
void ui_event_returnHomeB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Menu_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        clicked_daplink_to_menu(e);
    }
}
void ui_event_PDControlRoller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_daplinkPowerPDControlRollerValueChange(e);
    }
}
void ui_event_PDOutputEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_daplinkPowerPDOutputValueChange(e);
    }
}
void ui_event_FileExplorer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        cb_FileExplorerScreenLoad(e);
    }
}
void ui_event_OfflineDownload(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        cb_OfflineDownloadScreenLoad(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Title_Down_Animation(ui_OfflineDownloadTitle, 200);
        DAPLINK_HOME_UP_Animation(ui_ODreturnHome, 200);
    }
}
void ui_event_chooseDeviceB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FileExplorer, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_FileExplorer_screen_init);
        cb_offlineDownloadToFileExplorerChooseDevice(e);
    }
}
void ui_event_chooseBinB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FileExplorer, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_FileExplorer_screen_init);
        cb_offlineDownloadtoFileExplorerChooseBin(e);
    }
}
void ui_event_startOfflineDownloadB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        cb_clickedStartDownload(e);
    }
}
void ui_event_ODreturnHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Menu_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        clicked_OfflineDownload_to_menu(e);
    }
}
void ui_event_VoltAmmeter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        cb_VoltAmmeterScreenLoad(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Title_Down_Animation(ui_VoltAmmeterTitle, 200);
        DAPLINK_HOME_UP_Animation(ui_VAreturnHomeB, 200);
    }
}
void ui_event_VATabview(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        cb_clickedVoltAmmeterTB(e);
    }
}
void ui_event_VAOUTPUT5V0ENABLEB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_VAOUTPUT5V0ENABLEL, _UI_LABEL_PROPERTY_TEXT, "5V0 DISABLE");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_VAOUTPUT5V0ENABLEL, _UI_LABEL_PROPERTY_TEXT, "5V0 ENABLE");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_voltammeterPower5V0ButtonChanged(e);
    }
}
void ui_event_VAOUTPUT3V3ENABLEB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_VAOUTPUT3V3ENABLEL, _UI_LABEL_PROPERTY_TEXT, "3V3 DISABLE");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_VAOUTPUT3V3ENABLEL, _UI_LABEL_PROPERTY_TEXT, "3V3 ENABLE");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_voltammeterPower3V3ButtonChanged(e);
    }
}
void ui_event_VAOUTPUTPDENABLEB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_VAOUTPUTPDENABLEL, _UI_LABEL_PROPERTY_TEXT, "PD DISABLE");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_VAOUTPUTPDENABLEL, _UI_LABEL_PROPERTY_TEXT, "PD ENABLE");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_voltammeterPowerPDButtonChanged(e);
    }
}
void ui_event_VAPDOPTIONDropDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_voltammeterPowerPDDropdownChanged(e);
    }
}
void ui_event_VAreturnHomeB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Menu_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        cb_clickedVoltAmmeterToMenu(e);
    }
}
void ui_event_AboutreturnHomeB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Menu_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        cb_clickedVoltAmmeterToMenu(e);
    }
}
void ui_event_UartMonitor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        DAPLINK_HOME_UP_Animation(ui_UMreturnHomeB, 200);
        Title_Down_Animation(ui_UartMonitorTitle, 200);
    }
}
void ui_event_UMreturnHomeB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Menu_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        cb_clickedUartMonitorToMenu(e);
    }
}
void ui_event_UartMonitorBaud(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_UartMonitorBaudValueChange(e);
    }
}
void ui_event_UartMonitorParity(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_UartMonitorParityValueChange(e);
    }
}
void ui_event_PWMoutput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        pwmInfoLeftToShow_Animation(ui_pwmInfoContainer, 0);
        cb_PWMoutputScreenLoaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Title_Down_Animation(ui_PWMtitle, 200);
        DAPLINK_HOME_UP_Animation(ui_returnPWMHomeB, 200);
    }
}
void ui_event_returnPWMHomeB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Menu_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        clicked_PWMoutput_to_menu(e);
    }
}
void ui_event_TextAreaPeriod(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_PWMperiodValueChange(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        _ui_keyboard_set_target(ui_PWMKeyboard,  ui_TextAreaPeriod);
        pwmKeyboardup_Animation(ui_pwmKeyboardContainer, 0);
        cb_textAreaPeriodKeyEnter(e);
    }
}
void ui_event_TextAreaPulse(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_PWMPulseValueChange(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        _ui_keyboard_set_target(ui_PWMKeyboard,  ui_TextAreaPulse);
        pwmKeyboardup_Animation(ui_pwmKeyboardContainer, 0);
        cb_textAreaPulseKeyEnter(e);
    }
}
void ui_event_PWMKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_PWMkeyboardValueChanged(e);
    }
    if(event_code == LV_EVENT_READY) {
        cb_PWMkeyboardReady(e);
    }
    if(event_code == LV_EVENT_CANCEL) {
        cb_PWMkeyboardCancel(e);
    }
}
void ui_event_DACoutput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Title_Down_Animation(ui_DACtitle, 200);
        DAPLINK_HOME_UP_Animation(ui_returnDACHomeB, 200);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        cb_DACoutputScreenLoaded(e);
    }
}
void ui_event_returnDACHomeB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Menu_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        clicked_DAC_to_menu(e);
    }
}
void ui_event_KeyboardDAC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        cb_DACkeyboardReady(e);
    }
    if(event_code == LV_EVENT_CANCEL) {
        cb_DACkeyboardCancel(e);
    }
}
void ui_event_OutputWaveDP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_DACWAVEDropdownChanged(e);
    }
}
void ui_event_TextAreaWaveFrequencyVoltage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        DAC_PANEL_UP_Animation(ui_DACContainerPanel, 0);
        DAC_KEYBOARD_UP_Animation(ui_KeyboardDAC, 0);
        _ui_keyboard_set_target(ui_KeyboardDAC,  ui_TextAreaWaveFrequencyVoltage);
        cb_DACFrequencyTextareaEnter(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_DACFrequencyTextareaValueChanged(e);
    }
}
void ui_event_TextAreaDACVoltage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        DAC_PANEL_UP_Animation(ui_DACContainerPanel, 0);
        DAC_KEYBOARD_UP_Animation(ui_KeyboardDAC, 0);
        _ui_keyboard_set_target(ui_KeyboardDAC,  ui_TextAreaDACVoltage);
        cb_DACVoltageTextareaEnter(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_DACVoltageTextareaValueChanged(e);
    }
}
void ui_event_DACSelfWave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cb_DACSelfWaveTextareaValueChanged(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        DAC_PANEL_UP_Animation(ui_DACContainerPanel, 0);
        DAC_KEYBOARD_UP_Animation(ui_KeyboardDAC, 0);
        _ui_keyboard_set_target(ui_KeyboardDAC,  ui_DACSelfWave);
        cb_DACSelfWaveTextareaEnter(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_INIT_screen_init();
    ui_Menu_screen_init();
    // ui_DAPLINK_screen_init();
    // ui_OfflineDownload_screen_init();
    // ui_VoltAmmeter_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_INIT);
}
