// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void cb_loadedMenu(lv_event_t * e);
void cb_clicked_menu_to_daplink(lv_event_t * e);
void cb_clicked_menu_to_offline_download(lv_event_t * e);
void cb_screenToVoltAmmeter(lv_event_t * e);
void cb_screenToUartMonitor(lv_event_t * e);
void cb_menutoPWMscreen(lv_event_t * e);
void cb_menutoDACscreen(lv_event_t * e);
void cb_clicked_menu_to_file_explorer(lv_event_t * e);
void cb_DAPLINKScreenLoad(lv_event_t * e);
void cb_daplinkPower5V0cCheckBoxValueChange(lv_event_t * e);
void cb_daplinkPower3V3cCheckBoxValueChange(lv_event_t * e);
void clicked_daplink_to_menu(lv_event_t * e);
void cb_daplinkPowerPDControlRollerValueChange(lv_event_t * e);
void cb_daplinkPowerPDOutputValueChange(lv_event_t * e);
void cb_FileExplorerScreenLoad(lv_event_t * e);
void cb_OfflineDownloadScreenLoad(lv_event_t * e);
void cb_offlineDownloadToFileExplorerChooseDevice(lv_event_t * e);
void cb_offlineDownloadtoFileExplorerChooseBin(lv_event_t * e);
void cb_clickedStartDownload(lv_event_t * e);
void clicked_OfflineDownload_to_menu(lv_event_t * e);
void cb_VoltAmmeterScreenLoad(lv_event_t * e);
void cb_clickedVoltAmmeterTB(lv_event_t * e);
void cb_voltammeterPower5V0ButtonChanged(lv_event_t * e);
void cb_voltammeterPower3V3ButtonChanged(lv_event_t * e);
void cb_voltammeterPowerPDButtonChanged(lv_event_t * e);
void cb_voltammeterPowerPDDropdownChanged(lv_event_t * e);
void cb_clickedVoltAmmeterToMenu(lv_event_t * e);
void cb_clickedUartMonitorToMenu(lv_event_t * e);
void cb_UartMonitorBaudValueChange(lv_event_t * e);
void cb_UartMonitorParityValueChange(lv_event_t * e);
void cb_PWMoutputScreenLoaded(lv_event_t * e);
void clicked_PWMoutput_to_menu(lv_event_t * e);
void cb_PWMperiodValueChange(lv_event_t * e);
void cb_textAreaPeriodKeyEnter(lv_event_t * e);
void cb_PWMPulseValueChange(lv_event_t * e);
void cb_textAreaPulseKeyEnter(lv_event_t * e);
void cb_PWMkeyboardValueChanged(lv_event_t * e);
void cb_PWMkeyboardReady(lv_event_t * e);
void cb_PWMkeyboardCancel(lv_event_t * e);
void cb_DACoutputScreenLoaded(lv_event_t * e);
void clicked_DAC_to_menu(lv_event_t * e);
void cb_DACkeyboardReady(lv_event_t * e);
void cb_DACkeyboardCancel(lv_event_t * e);
void cb_DACWAVEDropdownChanged(lv_event_t * e);
void cb_DACFrequencyTextareaEnter(lv_event_t * e);
void cb_DACFrequencyTextareaValueChanged(lv_event_t * e);
void cb_DACVoltageTextareaEnter(lv_event_t * e);
void cb_DACVoltageTextareaValueChanged(lv_event_t * e);
void cb_DACSelfWaveTextareaValueChanged(lv_event_t * e);
void cb_DACSelfWaveTextareaEnter(lv_event_t * e);

void cb_menutoAboutscreen(lv_event_t * e);
	
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
