// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "screens.h"

extern lv_group_t *daplink_group;

void ui_DAPLINK_add_group(void)
{
    lv_group_set_editing(daplink_group, false);   //导航模式

    lv_group_add_obj(daplink_group, ui_Power5V0CheckBox);
    lv_group_add_obj(daplink_group, ui_Power3V3CheckBox);
    lv_group_add_obj(daplink_group, ui_PDControlRoller);
    lv_group_add_obj(daplink_group, ui_PDOutputEN);
    lv_group_add_obj(daplink_group, ui_returnHomeB);
}

void ui_DAPLINK_screen_init(void)
{
    current_screen_set(SCREEN_DAPLINK);

    if(daplink_group == NULL)
    {
        daplink_group = lv_group_create();
        lv_group_set_editing(daplink_group, false);   //导航模式
    }

    ui_DAPLINK = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DAPLINK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DAPLINK, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DAPLINK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title = lv_label_create(ui_DAPLINK);
    lv_obj_set_width(ui_title, 240);
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_title, "DAPLINK");
    lv_obj_set_style_text_color(ui_title, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_title, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_title, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DBG = lv_obj_create(ui_DAPLINK);
    lv_obj_remove_style_all(ui_DBG);
    lv_obj_set_height(ui_DBG, 67);
    lv_obj_set_width(ui_DBG, lv_pct(96));
    lv_obj_set_x(ui_DBG, 0);
    lv_obj_set_y(ui_DBG, 33);
    lv_obj_set_align(ui_DBG, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_DBG, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dbgModeB = lv_btn_create(ui_DBG);
    lv_obj_set_width(ui_dbgModeB, 100);
    lv_obj_set_height(ui_dbgModeB, 20);
    lv_obj_add_flag(ui_dbgModeB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dbgModeB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dbgModeB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dbgModeL = lv_label_create(ui_dbgModeB);
    lv_obj_set_width(ui_dbgModeL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dbgModeL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dbgModeL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dbgModeL, "SWD");
    lv_obj_set_style_text_font(ui_dbgModeL, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dbgClockB = lv_btn_create(ui_DBG);
    lv_obj_set_width(ui_dbgClockB, 100);
    lv_obj_set_height(ui_dbgClockB, 20);
    lv_obj_set_align(ui_dbgClockB, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_dbgClockB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dbgClockB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dbgClockB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dbgClockB, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dbgClockB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dbgClockL = lv_label_create(ui_dbgClockB);
    lv_obj_set_width(ui_dbgClockL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dbgClockL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dbgClockL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dbgClockL, "5M Hz");
    lv_obj_set_style_text_font(ui_dbgClockL, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dbgIDCODEB = lv_btn_create(ui_DBG);
    lv_obj_set_height(ui_dbgIDCODEB, 20);
    lv_obj_set_width(ui_dbgIDCODEB, lv_pct(100));
    lv_obj_set_x(ui_dbgIDCODEB, 0);
    lv_obj_set_y(ui_dbgIDCODEB, 1);
    lv_obj_set_align(ui_dbgIDCODEB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dbgIDCODEB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dbgIDCODEB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dbgIDCODEB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dbgIDCODEB, lv_color_hex(0x0073FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dbgIDCODEB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dbgIDCODEL = lv_label_create(ui_dbgIDCODEB);
    lv_obj_set_width(ui_dbgIDCODEL, lv_pct(100));
    lv_obj_set_height(ui_dbgIDCODEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dbgIDCODEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dbgIDCODEL, "IDCODE:   NONE");
    lv_obj_set_style_text_font(ui_dbgIDCODEL, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uartInfoB = lv_btn_create(ui_DBG);
    lv_obj_set_height(ui_uartInfoB, 20);
    lv_obj_set_width(ui_uartInfoB, lv_pct(100));
    lv_obj_set_align(ui_uartInfoB, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_uartInfoB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uartInfoB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uartInfoB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uartInfoB, lv_color_hex(0x0073FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uartInfoB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uartInfoL = lv_label_create(ui_uartInfoB);
    lv_obj_set_width(ui_uartInfoL, lv_pct(110));
    lv_obj_set_height(ui_uartInfoL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uartInfoL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uartInfoL, "UART:NOT OPEN");
    lv_obj_set_style_text_align(ui_uartInfoL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uartInfoL, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerPanel = lv_obj_create(ui_DAPLINK);
    lv_obj_remove_style_all(ui_PowerPanel);
    lv_obj_set_height(ui_PowerPanel, 58);
    lv_obj_set_width(ui_PowerPanel, lv_pct(96));
    lv_obj_set_x(ui_PowerPanel, 0);
    lv_obj_set_y(ui_PowerPanel, 15);
    lv_obj_set_align(ui_PowerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PowerPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PowerPanel, lv_color_hex(0x99CCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Power5V0CheckBox = lv_checkbox_create(ui_PowerPanel);
    lv_checkbox_set_text(ui_Power5V0CheckBox, "5V0");
    lv_obj_set_width(ui_Power5V0CheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Power5V0CheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Power5V0CheckBox, 6);
    lv_obj_set_y(ui_Power5V0CheckBox, 4);
    lv_obj_add_flag(ui_Power5V0CheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Power5V0CheckBox, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_outline_color(ui_Power5V0CheckBox, lv_color_hex(0x010101), LV_PART_INDICATOR | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Power5V0CheckBox, 255, LV_PART_INDICATOR | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_Power5V0CheckBox, 1, LV_PART_INDICATOR | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_Power5V0CheckBox, 0, LV_PART_INDICATOR | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_Power5V0CheckBox, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_Power5V0CheckBox, 255, LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_Power5V0CheckBox, 2, LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_Power5V0CheckBox, 2, LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);

    ui_Power3V3CheckBox = lv_checkbox_create(ui_PowerPanel);
    lv_checkbox_set_text(ui_Power3V3CheckBox, "3V3");
    lv_obj_set_width(ui_Power3V3CheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Power3V3CheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Power3V3CheckBox, 6);
    lv_obj_set_y(ui_Power3V3CheckBox, -1);
    lv_obj_set_align(ui_Power3V3CheckBox, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Power3V3CheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Power3V3CheckBox, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_outline_color(ui_Power3V3CheckBox, lv_color_hex(0x0091E6), LV_PART_INDICATOR | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Power3V3CheckBox, 255, LV_PART_INDICATOR | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_Power3V3CheckBox, 1, LV_PART_INDICATOR | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_Power3V3CheckBox, 3, LV_PART_INDICATOR | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_Power3V3CheckBox, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_Power3V3CheckBox, 255, LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_Power3V3CheckBox, 2, LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_Power3V3CheckBox, 2, LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);

    ui_POWER5VMeasure = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_POWER5VMeasure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POWER5VMeasure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POWER5VMeasure, -5);
    lv_obj_set_y(ui_POWER5VMeasure, 6);
    lv_obj_set_align(ui_POWER5VMeasure, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_POWER5VMeasure, "00.00V");
    lv_obj_set_style_text_align(ui_POWER5VMeasure, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POWER5VMeasure, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POWER3VMeasure = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_POWER3VMeasure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POWER3VMeasure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POWER3VMeasure, -5);
    lv_obj_set_y(ui_POWER3VMeasure, -3);
    lv_obj_set_align(ui_POWER3VMeasure, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_POWER3VMeasure, "00.00V");
    lv_obj_set_style_text_align(ui_POWER3VMeasure, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POWER3VMeasure, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POWER3CMeasure = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_POWER3CMeasure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POWER3CMeasure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POWER3CMeasure, -11);
    lv_obj_set_y(ui_POWER3CMeasure, -3);
    lv_obj_set_align(ui_POWER3CMeasure, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_POWER3CMeasure, "00.00mA");
    lv_obj_set_style_text_align(ui_POWER3CMeasure, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POWER3CMeasure, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POWER5CMeasure = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_POWER5CMeasure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POWER5CMeasure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POWER5CMeasure, -11);
    lv_obj_set_y(ui_POWER5CMeasure, 6);
    lv_obj_set_align(ui_POWER5CMeasure, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_POWER5CMeasure, "00.00mA");
    lv_obj_set_style_text_align(ui_POWER5CMeasure, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POWER5CMeasure, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnHomeB = lv_btn_create(ui_DAPLINK);
    lv_obj_set_height(ui_returnHomeB, 18);
    lv_obj_set_width(ui_returnHomeB, lv_pct(96));
    lv_obj_set_x(ui_returnHomeB, 0);
    lv_obj_set_y(ui_returnHomeB, -4);
    lv_obj_set_align(ui_returnHomeB, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_returnHomeB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_returnHomeB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_returnHomeB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_returnHomeB, lv_color_hex(0x0073FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnHomeB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_returnHomeB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_returnHomeB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_returnHomeB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_returnHomeB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_returnHomeL = lv_label_create(ui_returnHomeB);
    lv_obj_set_width(ui_returnHomeL, lv_pct(100));
    lv_obj_set_height(ui_returnHomeL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_returnHomeL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnHomeL, "Home");
    lv_label_set_recolor(ui_returnHomeL, "true");
    lv_obj_set_style_text_align(ui_returnHomeL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnHomeL, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PDPanel = lv_obj_create(ui_DAPLINK);
    lv_obj_remove_style_all(ui_PDPanel);
    lv_obj_set_height(ui_PDPanel, 47);
    lv_obj_set_width(ui_PDPanel, lv_pct(98));
    lv_obj_set_x(ui_PDPanel, -1);
    lv_obj_set_y(ui_PDPanel, 70);
    lv_obj_set_align(ui_PDPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PDPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PDControlRoller = lv_roller_create(ui_PDPanel);
    lv_roller_set_options(ui_PDControlRoller, "PD-5V\nPD-9V\nPD-12V\nPD-15V\nPD-20V", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_PDControlRoller, 40);
    lv_obj_set_width(ui_PDControlRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_PDControlRoller, 3);
    lv_obj_set_y(ui_PDControlRoller, 0);
    lv_obj_set_align(ui_PDControlRoller, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_text_letter_space(ui_PDControlRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PDControlRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PDControlRoller, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PDControlRoller, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PDControlRoller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PDControlRoller, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PDControlRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PDControlRoller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PDControlRoller, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PDControlRoller, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PDControlRoller, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_PDControlRoller, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_PDControlRoller, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_PDControlRoller, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_PDControlRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_PDControlRoller, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_PDControlRoller, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_PDControlRoller, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_blend_mode(ui_PDControlRoller, LV_BLEND_MODE_NORMAL, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_POWERPDVmeasure = lv_label_create(ui_PDPanel);
    lv_obj_set_width(ui_POWERPDVmeasure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POWERPDVmeasure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POWERPDVmeasure, -5);
    lv_obj_set_y(ui_POWERPDVmeasure, -9);
    lv_obj_set_align(ui_POWERPDVmeasure, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_POWERPDVmeasure, "00.000V");
    lv_obj_set_style_text_align(ui_POWERPDVmeasure, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POWERPDVmeasure, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POWERPDImeasure = lv_label_create(ui_PDPanel);
    lv_obj_set_width(ui_POWERPDImeasure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POWERPDImeasure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POWERPDImeasure, -5);
    lv_obj_set_y(ui_POWERPDImeasure, 14);
    lv_obj_set_align(ui_POWERPDImeasure, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_POWERPDImeasure, "00.00mA");
    lv_obj_set_style_text_align(ui_POWERPDImeasure, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POWERPDImeasure, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PDOutputEN = lv_switch_create(ui_PDPanel);
    lv_obj_set_width(ui_PDOutputEN, 50);
    lv_obj_set_height(ui_PDOutputEN, 25);
    lv_obj_set_x(ui_PDOutputEN, 8);
    lv_obj_set_y(ui_PDOutputEN, 0);
    lv_obj_set_align(ui_PDOutputEN, LV_ALIGN_CENTER);
    lv_obj_set_style_anim_time(ui_PDOutputEN, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PDOutputEN, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_PDOutputEN, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_PDOutputEN, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_PDOutputEN, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_PDOutputEN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_PDOutputEN, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_PDOutputEN, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_PDOutputEN, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_bg_color(ui_PDOutputEN, lv_color_hex(0xB92B27), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PDOutputEN, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PDOutputEN, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PDOutputEN, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PDOutputEN, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PDOutputEN, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PDOutputEN, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PDOutputEN, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PDOutputEN, lv_color_hex(0x00FF35), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PDOutputEN, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Power5V0CheckBox, ui_event_Power5V0CheckBox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Power3V3CheckBox, ui_event_Power3V3CheckBox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_returnHomeB, ui_event_returnHomeB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PDControlRoller, ui_event_PDControlRoller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PDOutputEN, ui_event_PDOutputEN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DAPLINK, ui_event_DAPLINK, LV_EVENT_ALL, NULL);

    ui_DAPLINK_add_group();
}

void ui_DAPLINK_screen_del(void)
{
    lv_obj_del(ui_DAPLINK);
    ui_DAPLINK = NULL;
}
