// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "screens.h"


extern lv_group_t *volt_ammeter_group_main;

void ui_VoltAmmeter_add_group(void)
{
    static lv_obj_t *va_tabview_btns1;
    va_tabview_btns1 = lv_tabview_get_tab_btns(ui_VATabview);
    lv_group_add_obj(volt_ammeter_group_main, va_tabview_btns1);
    lv_group_add_obj(volt_ammeter_group_main, ui_VAreturnHomeB);

    lv_group_set_editing(volt_ammeter_group_main, false);   //导航模式
}


void ui_VoltAmmeter_screen_init(void)
{
    current_screen_set(SCREEN_OFFLINE_DOWNLOAD);

    if(volt_ammeter_group_main == NULL)
    {
        volt_ammeter_group_main = lv_group_create();
        lv_group_set_editing(volt_ammeter_group_main, false);   //导航模式
    }

    ui_VoltAmmeter = lv_obj_create(NULL);
    lv_obj_add_flag(ui_VoltAmmeter, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_VoltAmmeter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VoltAmmeterTitle = lv_label_create(ui_VoltAmmeter);
    lv_obj_set_width(ui_VoltAmmeterTitle, 240);
    lv_obj_set_height(ui_VoltAmmeterTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VoltAmmeterTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_VoltAmmeterTitle, "电压电流表");
    lv_obj_set_style_text_color(ui_VoltAmmeterTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VoltAmmeterTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VoltAmmeterTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VoltAmmeterTitle, &ui_font_PuHuiTi25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VoltAmmeterTitle, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VoltAmmeterTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltAmmeterContainer = lv_obj_create(ui_VoltAmmeter);
    lv_obj_remove_style_all(ui_VoltAmmeterContainer);
    lv_obj_set_height(ui_VoltAmmeterContainer, 190);
    lv_obj_set_width(ui_VoltAmmeterContainer, lv_pct(100));
    lv_obj_set_x(ui_VoltAmmeterContainer, 0);
    lv_obj_set_y(ui_VoltAmmeterContainer, 4);
    lv_obj_set_align(ui_VoltAmmeterContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VoltAmmeterContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VATabview = lv_tabview_create(ui_VoltAmmeterContainer, LV_DIR_BOTTOM, 40);
    lv_obj_set_width(ui_VATabview, lv_pct(100));
    lv_obj_set_height(ui_VATabview, lv_pct(100));
    lv_obj_set_align(ui_VATabview, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VATabview, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_VATabview, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_VATabview), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_VATabview), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage5V0 = lv_tabview_add_tab(ui_VATabview, "5V0");
    lv_obj_set_flex_flow(ui_TabPage5V0, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabPage5V0, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_TabPage5V0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MPOWER5VMeasureB = lv_btn_create(ui_TabPage5V0);
    lv_obj_set_height(ui_MPOWER5VMeasureB, 35);
    lv_obj_set_width(ui_MPOWER5VMeasureB, lv_pct(100));
    lv_obj_set_align(ui_MPOWER5VMeasureB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPOWER5VMeasureB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MPOWER5VMeasureB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MPOWER5VMeasureB, lv_color_hex(0x00AEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MPOWER5VMeasureB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MPOWER5VMeasureB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MPOWER5VMeasureB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MPOWER5VMeasureB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MPOWER5VMeasureB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_MPOWER5VMeasureL = lv_label_create(ui_MPOWER5VMeasureB);
    lv_obj_set_width(ui_MPOWER5VMeasureL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPOWER5VMeasureL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MPOWER5VMeasureL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPOWER5VMeasureL, "00.00  V");
    lv_obj_set_style_text_color(ui_MPOWER5VMeasureL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPOWER5VMeasureL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MPOWER5VMeasureL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPOWER5VMeasureL, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MPOWER5IMeasureB = lv_btn_create(ui_TabPage5V0);
    lv_obj_set_height(ui_MPOWER5IMeasureB, 35);
    lv_obj_set_width(ui_MPOWER5IMeasureB, lv_pct(100));
    lv_obj_set_align(ui_MPOWER5IMeasureB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPOWER5IMeasureB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MPOWER5IMeasureB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MPOWER5IMeasureB, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MPOWER5IMeasureB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MPOWER5IMeasureB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MPOWER5IMeasureB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MPOWER5IMeasureB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MPOWER5IMeasureB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_MPOWER5IMeasureL = lv_label_create(ui_MPOWER5IMeasureB);
    lv_obj_set_width(ui_MPOWER5IMeasureL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPOWER5IMeasureL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MPOWER5IMeasureL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPOWER5IMeasureL, "00.00 mA");
    lv_obj_set_style_text_color(ui_MPOWER5IMeasureL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPOWER5IMeasureL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MPOWER5IMeasureL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPOWER5IMeasureL, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MPOWER5PMeasureB2 = lv_btn_create(ui_TabPage5V0);
    lv_obj_set_height(ui_MPOWER5PMeasureB2, 35);
    lv_obj_set_width(ui_MPOWER5PMeasureB2, lv_pct(100));
    lv_obj_set_align(ui_MPOWER5PMeasureB2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPOWER5PMeasureB2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MPOWER5PMeasureB2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MPOWER5PMeasureB2, lv_color_hex(0x40E0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MPOWER5PMeasureB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MPOWER5PMeasureB2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MPOWER5PMeasureB2, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MPOWER5PMeasureB2, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MPOWER5PMeasureB2, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_MPOWER5PMeasureL = lv_label_create(ui_MPOWER5PMeasureB2);
    lv_obj_set_width(ui_MPOWER5PMeasureL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPOWER5PMeasureL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MPOWER5PMeasureL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPOWER5PMeasureL, "00.00  W");
    lv_obj_set_style_text_color(ui_MPOWER5PMeasureL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPOWER5PMeasureL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MPOWER5PMeasureL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPOWER5PMeasureL, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage3V3 = lv_tabview_add_tab(ui_VATabview, "3V3");
    lv_obj_set_flex_flow(ui_TabPage3V3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabPage3V3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TabPage3V3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MPOWER3VMeasureB = lv_btn_create(ui_TabPage3V3);
    lv_obj_set_height(ui_MPOWER3VMeasureB, 35);
    lv_obj_set_width(ui_MPOWER3VMeasureB, lv_pct(100));
    lv_obj_set_align(ui_MPOWER3VMeasureB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPOWER3VMeasureB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MPOWER3VMeasureB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MPOWER3VMeasureB, lv_color_hex(0x00AEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MPOWER3VMeasureB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MPOWER3VMeasureB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MPOWER3VMeasureB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MPOWER3VMeasureB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MPOWER3VMeasureB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_MPOWER3VMeasureL = lv_label_create(ui_MPOWER3VMeasureB);
    lv_obj_set_width(ui_MPOWER3VMeasureL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPOWER3VMeasureL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MPOWER3VMeasureL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPOWER3VMeasureL, "00.00  V");
    lv_obj_set_style_text_color(ui_MPOWER3VMeasureL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPOWER3VMeasureL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MPOWER3VMeasureL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPOWER3VMeasureL, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MPOWER3IMeasureB = lv_btn_create(ui_TabPage3V3);
    lv_obj_set_height(ui_MPOWER3IMeasureB, 35);
    lv_obj_set_width(ui_MPOWER3IMeasureB, lv_pct(100));
    lv_obj_set_align(ui_MPOWER3IMeasureB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPOWER3IMeasureB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MPOWER3IMeasureB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MPOWER3IMeasureB, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MPOWER3IMeasureB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MPOWER3IMeasureB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MPOWER3IMeasureB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MPOWER3IMeasureB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MPOWER3IMeasureB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_MPOWER3IMeasureL = lv_label_create(ui_MPOWER3IMeasureB);
    lv_obj_set_width(ui_MPOWER3IMeasureL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPOWER3IMeasureL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MPOWER3IMeasureL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPOWER3IMeasureL, "00.00 mA");
    lv_obj_set_style_text_color(ui_MPOWER3IMeasureL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPOWER3IMeasureL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MPOWER3IMeasureL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPOWER3IMeasureL, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MPOWER3PMeasureB = lv_btn_create(ui_TabPage3V3);
    lv_obj_set_height(ui_MPOWER3PMeasureB, 35);
    lv_obj_set_width(ui_MPOWER3PMeasureB, lv_pct(100));
    lv_obj_set_align(ui_MPOWER3PMeasureB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPOWER3PMeasureB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MPOWER3PMeasureB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MPOWER3PMeasureB, lv_color_hex(0x40E0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MPOWER3PMeasureB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MPOWER3PMeasureB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MPOWER3PMeasureB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MPOWER3PMeasureB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MPOWER3PMeasureB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_MPOWER3PMeasureL = lv_label_create(ui_MPOWER3PMeasureB);
    lv_obj_set_width(ui_MPOWER3PMeasureL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPOWER3PMeasureL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MPOWER3PMeasureL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPOWER3PMeasureL, "00.00  W");
    lv_obj_set_style_text_color(ui_MPOWER3PMeasureL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPOWER3PMeasureL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MPOWER3PMeasureL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPOWER3PMeasureL, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPagePD = lv_tabview_add_tab(ui_VATabview, "PD");
    lv_obj_set_flex_flow(ui_TabPagePD, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabPagePD, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TabPagePD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MPOWERPDVMeasureB = lv_btn_create(ui_TabPagePD);
    lv_obj_set_height(ui_MPOWERPDVMeasureB, 35);
    lv_obj_set_width(ui_MPOWERPDVMeasureB, lv_pct(100));
    lv_obj_set_align(ui_MPOWERPDVMeasureB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPOWERPDVMeasureB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MPOWERPDVMeasureB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MPOWERPDVMeasureB, lv_color_hex(0x00AEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MPOWERPDVMeasureB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MPOWERPDVMeasureB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MPOWERPDVMeasureB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MPOWERPDVMeasureB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MPOWERPDVMeasureB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_MPOWERPDVMeasureL = lv_label_create(ui_MPOWERPDVMeasureB);
    lv_obj_set_width(ui_MPOWERPDVMeasureL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPOWERPDVMeasureL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MPOWERPDVMeasureL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPOWERPDVMeasureL, "00.00  V");
    lv_obj_set_style_text_color(ui_MPOWERPDVMeasureL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPOWERPDVMeasureL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MPOWERPDVMeasureL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPOWERPDVMeasureL, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MPOWERPDIMeasureB = lv_btn_create(ui_TabPagePD);
    lv_obj_set_height(ui_MPOWERPDIMeasureB, 35);
    lv_obj_set_width(ui_MPOWERPDIMeasureB, lv_pct(100));
    lv_obj_set_align(ui_MPOWERPDIMeasureB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPOWERPDIMeasureB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MPOWERPDIMeasureB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MPOWERPDIMeasureB, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MPOWERPDIMeasureB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MPOWERPDIMeasureB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MPOWERPDIMeasureB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MPOWERPDIMeasureB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MPOWERPDIMeasureB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_MPOWERPDIMeasureL = lv_label_create(ui_MPOWERPDIMeasureB);
    lv_obj_set_width(ui_MPOWERPDIMeasureL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPOWERPDIMeasureL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MPOWERPDIMeasureL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPOWERPDIMeasureL, "00.00 mA");
    lv_obj_set_style_text_color(ui_MPOWERPDIMeasureL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPOWERPDIMeasureL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MPOWERPDIMeasureL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPOWERPDIMeasureL, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MPOWERPDPMeasureB = lv_btn_create(ui_TabPagePD);
    lv_obj_set_height(ui_MPOWERPDPMeasureB, 35);
    lv_obj_set_width(ui_MPOWERPDPMeasureB, lv_pct(100));
    lv_obj_set_align(ui_MPOWERPDPMeasureB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPOWERPDPMeasureB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MPOWERPDPMeasureB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MPOWERPDPMeasureB, lv_color_hex(0x40E0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MPOWERPDPMeasureB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MPOWERPDPMeasureB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MPOWERPDPMeasureB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MPOWERPDPMeasureB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MPOWERPDPMeasureB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_MPOWERPDPMeasureL = lv_label_create(ui_MPOWERPDPMeasureB);
    lv_obj_set_width(ui_MPOWERPDPMeasureL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPOWERPDPMeasureL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MPOWERPDPMeasureL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPOWERPDPMeasureL, "00.00  W");
    lv_obj_set_style_text_color(ui_MPOWERPDPMeasureL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPOWERPDPMeasureL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MPOWERPDPMeasureL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPOWERPDPMeasureL, &ui_font_jetbrainsMonoMedium25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPageSet = lv_tabview_add_tab(ui_VATabview, "SET");
    lv_obj_set_flex_flow(ui_TabPageSet, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabPageSet, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TabPageSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VAOUTPUT5V0ENABLEB = lv_btn_create(ui_TabPageSet);
    lv_obj_set_height(ui_VAOUTPUT5V0ENABLEB, 20);
    lv_obj_set_width(ui_VAOUTPUT5V0ENABLEB, lv_pct(100));
    lv_obj_set_align(ui_VAOUTPUT5V0ENABLEB, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_VAOUTPUT5V0ENABLEB, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_VAOUTPUT5V0ENABLEB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VAOUTPUT5V0ENABLEB, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VAOUTPUT5V0ENABLEB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_VAOUTPUT5V0ENABLEB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_VAOUTPUT5V0ENABLEB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_VAOUTPUT5V0ENABLEB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_VAOUTPUT5V0ENABLEB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_VAOUTPUT5V0ENABLEL = lv_label_create(ui_VAOUTPUT5V0ENABLEB);
    lv_obj_set_width(ui_VAOUTPUT5V0ENABLEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VAOUTPUT5V0ENABLEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VAOUTPUT5V0ENABLEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VAOUTPUT5V0ENABLEL, "5V0 ENABLE");
    lv_obj_set_style_text_color(ui_VAOUTPUT5V0ENABLEL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VAOUTPUT5V0ENABLEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VAOUTPUT5V0ENABLEL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VAOUTPUT5V0ENABLEL, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VAOUTPUT3V3ENABLEB = lv_btn_create(ui_TabPageSet);
    lv_obj_set_height(ui_VAOUTPUT3V3ENABLEB, 20);
    lv_obj_set_width(ui_VAOUTPUT3V3ENABLEB, lv_pct(100));
    lv_obj_set_x(ui_VAOUTPUT3V3ENABLEB, 0);
    lv_obj_set_y(ui_VAOUTPUT3V3ENABLEB, -25);
    lv_obj_set_align(ui_VAOUTPUT3V3ENABLEB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VAOUTPUT3V3ENABLEB, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_VAOUTPUT3V3ENABLEB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VAOUTPUT3V3ENABLEB, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VAOUTPUT3V3ENABLEB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_VAOUTPUT3V3ENABLEB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_VAOUTPUT3V3ENABLEB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_VAOUTPUT3V3ENABLEB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_VAOUTPUT3V3ENABLEB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_VAOUTPUT3V3ENABLEL = lv_label_create(ui_VAOUTPUT3V3ENABLEB);
    lv_obj_set_width(ui_VAOUTPUT3V3ENABLEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VAOUTPUT3V3ENABLEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VAOUTPUT3V3ENABLEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VAOUTPUT3V3ENABLEL, "3V3 ENABLE");
    lv_obj_set_style_text_color(ui_VAOUTPUT3V3ENABLEL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VAOUTPUT3V3ENABLEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VAOUTPUT3V3ENABLEL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VAOUTPUT3V3ENABLEL, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VAOUTPUTPDENABLEB = lv_btn_create(ui_TabPageSet);
    lv_obj_set_height(ui_VAOUTPUTPDENABLEB, 20);
    lv_obj_set_width(ui_VAOUTPUTPDENABLEB, lv_pct(100));
    lv_obj_set_x(ui_VAOUTPUTPDENABLEB, 0);
    lv_obj_set_y(ui_VAOUTPUTPDENABLEB, 20);
    lv_obj_set_align(ui_VAOUTPUTPDENABLEB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VAOUTPUTPDENABLEB, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_VAOUTPUTPDENABLEB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VAOUTPUTPDENABLEB, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VAOUTPUTPDENABLEB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_VAOUTPUTPDENABLEB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_VAOUTPUTPDENABLEB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_VAOUTPUTPDENABLEB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_VAOUTPUTPDENABLEB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_VAOUTPUTPDENABLEL = lv_label_create(ui_VAOUTPUTPDENABLEB);
    lv_obj_set_width(ui_VAOUTPUTPDENABLEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VAOUTPUTPDENABLEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VAOUTPUTPDENABLEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VAOUTPUTPDENABLEL, "PD ENABLE");
    lv_obj_set_style_text_color(ui_VAOUTPUTPDENABLEL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VAOUTPUTPDENABLEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VAOUTPUTPDENABLEL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VAOUTPUTPDENABLEL, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VAPDSinkControl = lv_obj_create(ui_TabPageSet);
    lv_obj_remove_style_all(ui_VAPDSinkControl);
    lv_obj_set_height(ui_VAPDSinkControl, 40);
    lv_obj_set_width(ui_VAPDSinkControl, lv_pct(100));
    lv_obj_set_align(ui_VAPDSinkControl, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VAPDSinkControl, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VAPDSinkControl, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VAPDSinkControl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VAPDOPTIONDropDown = lv_dropdown_create(ui_VAPDSinkControl);
    lv_dropdown_set_options(ui_VAPDOPTIONDropDown, "PD 5V\nPD 9V\nPD 12V\nPD 15V\nPD 20V");
    lv_obj_set_width(ui_VAPDOPTIONDropDown, lv_pct(65));
    lv_obj_set_height(ui_VAPDOPTIONDropDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VAPDOPTIONDropDown, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_VAPDOPTIONDropDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_VAPDOPTIONDropDown, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_PDSinkState = lv_btn_create(ui_VAPDSinkControl);
    lv_obj_set_width(ui_PDSinkState, 30);
    lv_obj_set_height(ui_PDSinkState, 30);
    lv_obj_set_align(ui_PDSinkState, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PDSinkState, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PDSinkState, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PDSinkState, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PDSinkState, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PDSinkState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PDSinkState, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PDSinkState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VAreturnHomeB = lv_btn_create(ui_VoltAmmeter);
    lv_obj_set_height(ui_VAreturnHomeB, 18);
    lv_obj_set_width(ui_VAreturnHomeB, lv_pct(98));
    lv_obj_set_x(ui_VAreturnHomeB, 0);
    lv_obj_set_y(ui_VAreturnHomeB, -2);
    lv_obj_set_align(ui_VAreturnHomeB, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_VAreturnHomeB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_VAreturnHomeB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VAreturnHomeB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VAreturnHomeB, lv_color_hex(0x0073FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VAreturnHomeB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_VAreturnHomeB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_VAreturnHomeB, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_VAreturnHomeB, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_VAreturnHomeB, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_VAreturnHomeL = lv_label_create(ui_VAreturnHomeB);
    lv_obj_set_width(ui_VAreturnHomeL, lv_pct(100));
    lv_obj_set_height(ui_VAreturnHomeL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VAreturnHomeL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VAreturnHomeL, "Home");
    lv_label_set_recolor(ui_VAreturnHomeL, "true");
    lv_obj_set_style_text_align(ui_VAreturnHomeL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VAreturnHomeL, &ui_font_jetbrainsMonoMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_VAOUTPUT5V0ENABLEB, ui_event_VAOUTPUT5V0ENABLEB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VAOUTPUT3V3ENABLEB, ui_event_VAOUTPUT3V3ENABLEB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VAOUTPUTPDENABLEB, ui_event_VAOUTPUTPDENABLEB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VAPDOPTIONDropDown, ui_event_VAPDOPTIONDropDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VATabview, ui_event_VATabview, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VAreturnHomeB, ui_event_VAreturnHomeB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VoltAmmeter, ui_event_VoltAmmeter, LV_EVENT_ALL, NULL);

    ui_VoltAmmeter_add_group();
}



void ui_VoltAmmeter_screen_del(void)
{
    lv_obj_del(ui_VoltAmmeter);
    ui_VoltAmmeter = NULL;
}
