// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "screens.h"

void ui_INIT_screen_init(void)
{
    current_screen_set(SCREEN_INIT);

    ui_INIT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_INIT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infoTitle = lv_label_create(ui_INIT);
    lv_obj_set_width(ui_infoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_infoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_infoTitle, 0);
    lv_obj_set_y(ui_infoTitle, 10);
    lv_obj_set_align(ui_infoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_infoTitle, "立创开发板\n多功能调试工具");
    lv_obj_set_style_text_color(ui_infoTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_infoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_infoTitle, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_infoTitle, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_infoTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_infoTitle, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slogan = lv_label_create(ui_INIT);
    lv_obj_set_width(ui_slogan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slogan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_slogan, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_slogan, "不靠卖板赚钱\n以培养中国工程师为己任");
    lv_obj_set_style_text_align(ui_slogan, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slogan, &ui_font_PuHuiTi, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoAndTextContainer = lv_obj_create(ui_INIT);
    lv_obj_remove_style_all(ui_logoAndTextContainer);
    lv_obj_set_height(ui_logoAndTextContainer, 57);
    lv_obj_set_width(ui_logoAndTextContainer, lv_pct(98));
    lv_obj_set_x(ui_logoAndTextContainer, 0);
    lv_obj_set_y(ui_logoAndTextContainer, 5);
    lv_obj_set_align(ui_logoAndTextContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_logoAndTextContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoLite = lv_img_create(ui_logoAndTextContainer);
    lv_img_set_src(ui_LogoLite, &ui_img_743788411);
    lv_obj_set_width(ui_LogoLite, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_LogoLite, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_align(ui_LogoLite, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_LogoLite, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoLite, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoTitle = lv_label_create(ui_logoAndTextContainer);
    lv_obj_set_width(ui_LogoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoTitle, -4);
    lv_obj_set_y(ui_LogoTitle, 3);
    lv_obj_set_align(ui_LogoTitle, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LogoTitle, "立创开发板");
    lv_obj_set_style_text_color(ui_LogoTitle, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LogoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LogoTitle, &ui_font_PuHuiTi30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoWebsite = lv_label_create(ui_logoAndTextContainer);
    lv_obj_set_width(ui_LogoWebsite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoWebsite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoWebsite, -13);
    lv_obj_set_y(ui_LogoWebsite, -2);
    lv_obj_set_align(ui_LogoWebsite, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_LogoWebsite, "WWW.LCKFB.COM");
    lv_obj_set_style_text_color(ui_LogoWebsite, lv_color_hex(0x0091E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LogoWebsite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LogoWebsite, &ui_font_jetbrainsMonoMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_INIT, ui_event_INIT, LV_EVENT_ALL, NULL);

}

void ui_INIT_screen_del(void)
{
    lv_obj_del(ui_INIT);
    ui_INIT = NULL;
}
