from building import *
import os

cwd = GetCurrentDir()
group = []
with open(os.path.join(cwd, '..', 'filelist.txt')) as filelist:
    src = [os.path.join(cwd, '..', path.strip()) for path in filelist if path.startswith('fonts/')]
CPPPATH = [cwd]

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

group = group + DefineGroup('UI', src, depend = ['PKG_USING_LVGL'], CPPPATH = CPPPATH)

Return('group')
