// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void ZOOM_LOGO_Animation(lv_obj_t * TargetObject, int delay);
void SHOW_SLOGAN_Animation(lv_obj_t * TargetObject, int delay);
void Title_Down_Animation(lv_obj_t * TargetObject, int delay);
void DAPLINK_HOME_UP_Animation(lv_obj_t * TargetObject, int delay);
void pwmKeyboardup_Animation(lv_obj_t * TargetObject, int delay);
void pwmKeyboarddown_Animation(lv_obj_t * TargetObject, int delay);
void pwmInfoLeftToShow_Animation(lv_obj_t * TargetObject, int delay);
void pwmInfoShowToRight_Animation(lv_obj_t * TargetObject, int delay);
void ZOOM_LCSC_Animation(lv_obj_t * TargetObject, int delay);
void LOGO_TITLE_DOWN_Animation(lv_obj_t * TargetObject, int delay);
void LOGO_WEBSITE_LEFT_Animation(lv_obj_t * TargetObject, int delay);
void DAC_KEYBOARD_UP_Animation(lv_obj_t * TargetObject, int delay);
void DAC_KEYBOARD_DOWN_Animation(lv_obj_t * TargetObject, int delay);
void DAC_PANEL_UP_Animation(lv_obj_t * TargetObject, int delay);
void DAC_PANEL_DOWN_Animation(lv_obj_t * TargetObject, int delay);
void ENLARGE_MENU_OBJ_Animation(lv_obj_t * TargetObject, int delay);
void DISLARGE_MENU_OBJ_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_INIT
void ui_INIT_screen_init(void);
void ui_event_INIT(lv_event_t * e);
extern lv_obj_t * ui_INIT;
extern lv_obj_t * ui_infoTitle;
extern lv_obj_t * ui_slogan;
extern lv_obj_t * ui_logoAndTextContainer;
extern lv_obj_t * ui_LogoLite;
extern lv_obj_t * ui_LogoTitle;
extern lv_obj_t * ui_LogoWebsite;
// SCREEN: ui_Menu
void ui_Menu_screen_init(void);
void ui_event_Menu(lv_event_t * e);
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui_menuPanel;
void ui_event_menuDAPLINKB(lv_event_t * e);
extern lv_obj_t * ui_menuDAPLINKB;
extern lv_obj_t * ui_menuDAPLINKL;
void ui_event_menuOfflineB(lv_event_t * e);
extern lv_obj_t * ui_menuOfflineB;
extern lv_obj_t * ui_menuOfflineL;
void ui_event_menuAmmeterB(lv_event_t * e);
extern lv_obj_t * ui_menuAmmeterB;
extern lv_obj_t * ui_menuAmmeterL;
void ui_event_menuUARTB(lv_event_t * e);
extern lv_obj_t * ui_menuUARTB;
extern lv_obj_t * ui_menuUARTL;
void ui_event_menuPWMB(lv_event_t * e);
extern lv_obj_t * ui_menuPWMB;
extern lv_obj_t * ui_menuPWML;
void ui_event_menuDACOutputB(lv_event_t * e);
extern lv_obj_t * ui_menuDACOutputB;
extern lv_obj_t * ui_menuDACOutputL;
void ui_event_menuSDCardB(lv_event_t * e);
extern lv_obj_t * ui_menuSDCardB;
extern lv_obj_t * ui_menuSDCardL;
extern lv_obj_t * ui_logoAndTextContainer2;
extern lv_obj_t * ui_LogoLite2;
extern lv_obj_t * ui_LogoTitle2;
extern lv_obj_t * ui_LogoWebsite2;

void ui_event_menuAboutB(lv_event_t * e);
extern lv_obj_t * ui_menuAboutB;
extern lv_obj_t * ui_menuAboutL;

// SCREEN: ui_DAPLINK
void ui_DAPLINK_screen_init(void);
void ui_event_DAPLINK(lv_event_t * e);
extern lv_obj_t * ui_DAPLINK;
extern lv_obj_t * ui_title;
extern lv_obj_t * ui_DBG;
extern lv_obj_t * ui_dbgModeB;
extern lv_obj_t * ui_dbgModeL;
extern lv_obj_t * ui_dbgClockB;
extern lv_obj_t * ui_dbgClockL;
extern lv_obj_t * ui_dbgIDCODEB;
extern lv_obj_t * ui_dbgIDCODEL;
extern lv_obj_t * ui_uartInfoB;
extern lv_obj_t * ui_uartInfoL;
extern lv_obj_t * ui_PowerPanel;
void ui_event_Power5V0CheckBox(lv_event_t * e);
extern lv_obj_t * ui_Power5V0CheckBox;
void ui_event_Power3V3CheckBox(lv_event_t * e);
extern lv_obj_t * ui_Power3V3CheckBox;
extern lv_obj_t * ui_POWER5VMeasure;
extern lv_obj_t * ui_POWER3VMeasure;
extern lv_obj_t * ui_POWER3CMeasure;
extern lv_obj_t * ui_POWER5CMeasure;
void ui_event_returnHomeB(lv_event_t * e);
extern lv_obj_t * ui_returnHomeB;
extern lv_obj_t * ui_returnHomeL;
extern lv_obj_t * ui_PDPanel;
void ui_event_PDControlRoller(lv_event_t * e);
extern lv_obj_t * ui_PDControlRoller;
extern lv_obj_t * ui_POWERPDVmeasure;
extern lv_obj_t * ui_POWERPDImeasure;
void ui_event_PDOutputEN(lv_event_t * e);
extern lv_obj_t * ui_PDOutputEN;
// SCREEN: ui_FileExplorer
void ui_FileExplorer_screen_init(void);
void ui_event_FileExplorer(lv_event_t * e);
extern lv_obj_t * ui_FileExplorer;
extern lv_obj_t * ui_FileExplorerTitle;
// SCREEN: ui_OfflineDownload
void ui_OfflineDownload_screen_init(void);
void ui_event_OfflineDownload(lv_event_t * e);
extern lv_obj_t * ui_OfflineDownload;
extern lv_obj_t * ui_OfflineDownloadTitle;
extern lv_obj_t * ui_OfflineDownloadContainer;
extern lv_obj_t * ui_OfflineDownloadProcessBar;
extern lv_obj_t * ui_OfflineDownloadProcessNum;
extern lv_obj_t * ui_offlineDownloadButtonContainer;
void ui_event_chooseDeviceB(lv_event_t * e);
extern lv_obj_t * ui_chooseDeviceB;
extern lv_obj_t * ui_chooseDeviceL;
void ui_event_chooseBinB(lv_event_t * e);
extern lv_obj_t * ui_chooseBinB;
extern lv_obj_t * ui_chooseBinL;
void ui_event_startOfflineDownloadB(lv_event_t * e);
extern lv_obj_t * ui_startOfflineDownloadB;
extern lv_obj_t * ui_startOfflineDownloadL;
extern lv_obj_t * ui_downloadConfigureB;
extern lv_obj_t * ui_downloadConfigureL;
extern lv_obj_t * ui_currentDevicePath;
extern lv_obj_t * ui_currentBinPath;
extern lv_obj_t * ui_offlineDownloadInfoContainer;
extern lv_obj_t * ui_ODdownloadSuccessCountT;
extern lv_obj_t * ui_ODdownloadSuccessCount;
extern lv_obj_t * ui_ODdownloadInfo;
void ui_event_ODreturnHome(lv_event_t * e);
extern lv_obj_t * ui_ODreturnHome;
extern lv_obj_t * ui_ODreturnHomeL;
// SCREEN: ui_VoltAmmeter
void ui_VoltAmmeter_screen_init(void);
void ui_event_VoltAmmeter(lv_event_t * e);
extern lv_obj_t * ui_VoltAmmeter;
extern lv_obj_t * ui_VoltAmmeterTitle;
extern lv_obj_t * ui_VoltAmmeterContainer;
void ui_event_VATabview(lv_event_t * e);
extern lv_obj_t * ui_VATabview;
extern lv_obj_t * ui_TabPage5V0;
extern lv_obj_t * ui_MPOWER5VMeasureB;
extern lv_obj_t * ui_MPOWER5VMeasureL;
extern lv_obj_t * ui_MPOWER5IMeasureB;
extern lv_obj_t * ui_MPOWER5IMeasureL;
extern lv_obj_t * ui_MPOWER5PMeasureB2;
extern lv_obj_t * ui_MPOWER5PMeasureL;
extern lv_obj_t * ui_TabPage3V3;
extern lv_obj_t * ui_MPOWER3VMeasureB;
extern lv_obj_t * ui_MPOWER3VMeasureL;
extern lv_obj_t * ui_MPOWER3IMeasureB;
extern lv_obj_t * ui_MPOWER3IMeasureL;
extern lv_obj_t * ui_MPOWER3PMeasureB;
extern lv_obj_t * ui_MPOWER3PMeasureL;
extern lv_obj_t * ui_TabPagePD;
extern lv_obj_t * ui_MPOWERPDVMeasureB;
extern lv_obj_t * ui_MPOWERPDVMeasureL;
extern lv_obj_t * ui_MPOWERPDIMeasureB;
extern lv_obj_t * ui_MPOWERPDIMeasureL;
extern lv_obj_t * ui_MPOWERPDPMeasureB;
extern lv_obj_t * ui_MPOWERPDPMeasureL;
extern lv_obj_t * ui_TabPageSet;
void ui_event_VAOUTPUT5V0ENABLEB(lv_event_t * e);
extern lv_obj_t * ui_VAOUTPUT5V0ENABLEB;
extern lv_obj_t * ui_VAOUTPUT5V0ENABLEL;
void ui_event_VAOUTPUT3V3ENABLEB(lv_event_t * e);
extern lv_obj_t * ui_VAOUTPUT3V3ENABLEB;
extern lv_obj_t * ui_VAOUTPUT3V3ENABLEL;
void ui_event_VAOUTPUTPDENABLEB(lv_event_t * e);
extern lv_obj_t * ui_VAOUTPUTPDENABLEB;
extern lv_obj_t * ui_VAOUTPUTPDENABLEL;
extern lv_obj_t * ui_VAPDSinkControl;
void ui_event_VAPDOPTIONDropDown(lv_event_t * e);
extern lv_obj_t * ui_VAPDOPTIONDropDown;
extern lv_obj_t * ui_PDSinkState;
void ui_event_VAreturnHomeB(lv_event_t * e);
extern lv_obj_t * ui_VAreturnHomeB;
extern lv_obj_t * ui_VAreturnHomeL;
// SCREEN: ui_UartMonitor
void ui_UartMonitor_screen_init(void);
void ui_event_UartMonitor(lv_event_t * e);
extern lv_obj_t * ui_UartMonitor;
void ui_event_UMreturnHomeB(lv_event_t * e);
extern lv_obj_t * ui_UMreturnHomeB;
extern lv_obj_t * ui_UMreturnHomeL;
extern lv_obj_t * ui_UartMonitorTitle;
extern lv_obj_t * ui_UartMonitorContainer;
void ui_event_UartMonitorBaud(lv_event_t * e);
extern lv_obj_t * ui_UartMonitorBaud;
void ui_event_UartMonitorParity(lv_event_t * e);
extern lv_obj_t * ui_UartMonitorParity;
extern lv_obj_t * ui_UMTextAreaContainer;
extern lv_obj_t * ui_UMTextArea;
// SCREEN: ui_PWMoutput
void ui_PWMoutput_screen_init(void);
void ui_event_PWMoutput(lv_event_t * e);
extern lv_obj_t * ui_PWMoutput;
extern lv_obj_t * ui_PWMtitle;
void ui_event_returnPWMHomeB(lv_event_t * e);
extern lv_obj_t * ui_returnPWMHomeB;
extern lv_obj_t * ui_returnPWMHomeL;
extern lv_obj_t * ui_PWMContainer;
extern lv_obj_t * ui_PeriodContainer;
extern lv_obj_t * ui_PeriodLabel;
void ui_event_TextAreaPeriod(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPeriod;
extern lv_obj_t * ui_PulseContainer;
extern lv_obj_t * ui_PulseLabel;
void ui_event_TextAreaPulse(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPulse;
extern lv_obj_t * ui_pwmKeyboardContainer;
void ui_event_PWMKeyboard(lv_event_t * e);
extern lv_obj_t * ui_PWMKeyboard;
extern lv_obj_t * ui_pwmInfoContainer;
extern lv_obj_t * ui_PWMfrequencyLabelInfo;
extern lv_obj_t * ui_PWMDutyCyclelabelInfo;
extern lv_obj_t * ui_PWMfrequencyLabel;
extern lv_obj_t * ui_PWMDutyCyclelabel;
// SCREEN: ui_DACoutput
void ui_DACoutput_screen_init(void);
void ui_event_DACoutput(lv_event_t * e);
extern lv_obj_t * ui_DACoutput;
extern lv_obj_t * ui_DACtitle;
void ui_event_returnDACHomeB(lv_event_t * e);
extern lv_obj_t * ui_returnDACHomeB;
extern lv_obj_t * ui_returnDACHomeL;
extern lv_obj_t * ui_DACContainer;
void ui_event_KeyboardDAC(lv_event_t * e);
extern lv_obj_t * ui_KeyboardDAC;
extern lv_obj_t * ui_DACContainerPanel;
extern lv_obj_t * ui_OutputWaveContainer;
extern lv_obj_t * ui_OutputWaveLabel;
void ui_event_OutputWaveDP(lv_event_t * e);
extern lv_obj_t * ui_OutputWaveDP;
extern lv_obj_t * ui_OutputWaveFrequencyContainer;
extern lv_obj_t * ui_OutputWaveFrequencyLabel;
void ui_event_TextAreaWaveFrequencyVoltage(lv_event_t * e);
extern lv_obj_t * ui_TextAreaWaveFrequencyVoltage;
extern lv_obj_t * ui_OutputVoltageContainer;
extern lv_obj_t * ui_OutputVoltageLabel;
void ui_event_TextAreaDACVoltage(lv_event_t * e);
extern lv_obj_t * ui_TextAreaDACVoltage;
extern lv_obj_t * ui_OutputSelfWaveContainer;
extern lv_obj_t * ui_OutputSelfWaveLabel;
void ui_event_DACSelfWave(lv_event_t * e);
extern lv_obj_t * ui_DACSelfWave;
extern lv_obj_t * ui____initial_actions0;
// SCREEN: ui_About
void ui_event_AboutreturnHomeB(lv_event_t * e);
void ui_About_screen_init(void);
extern lv_obj_t * ui_About;
extern lv_obj_t * ui_Abouttitle;
extern lv_obj_t * ui_AboutHomeB;
extern lv_obj_t * ui_AboutHomeL;
extern lv_obj_t * ui_AboutContainerPanel;


LV_FONT_DECLARE(ui_font_jetbrainsMonoMedium16);
LV_FONT_DECLARE(ui_font_jetbrainsMonoMedium20);
LV_FONT_DECLARE(ui_font_jetbrainsMonoMedium25);
LV_FONT_DECLARE(ui_font_PuHuiTi);
LV_FONT_DECLARE(ui_font_PuhuiTi20);
LV_FONT_DECLARE(ui_font_PuHuiTi25);
LV_FONT_DECLARE(ui_font_PuHuiTi30);
LV_FONT_DECLARE(ui_font_PuHuiTi35);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
