// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void cb_loadedMenu(lv_event_t * e);
void cb_clicked_menu_to_daplink(lv_event_t * e);
void cb_clicked_menu_to_offline_download(lv_event_t * e);
void cb_screenToVoltAmmeter(lv_event_t * e);
void cb_screenToUartMonitor(lv_event_t * e);
void cb_menutoPWMscreen(lv_event_t * e);
void cb_menutoDACscreen(lv_event_t * e);
void cb_clicked_menu_to_file_explorer(lv_event_t * e);
void cb_DAPLINKScreenLoad(lv_event_t * e);
void cb_daplinkPower5V0cCheckBoxValueChange(lv_event_t * e);
void cb_daplinkPower3V3cCheckBoxValueChange(lv_event_t * e);
void clicked_daplink_to_menu(lv_event_t * e);
void cb_daplinkPowerPDControlRollerValueChange(lv_event_t * e);
void cb_daplinkPowerPDOutputValueChange(lv_event_t * e);
void cb_FileExplorerScreenLoad(lv_event_t * e);
void cb_OfflineDownloadScreenLoad(lv_event_t * e);
void cb_offlineDownloadToFileExplorerChooseDevice(lv_event_t * e);
void cb_offlineDownloadtoFileExplorerChooseBin(lv_event_t * e);
void cb_clickedStartDownload(lv_event_t * e);
void clicked_OfflineDownload_to_menu(lv_event_t * e);
void cb_VoltAmmeterScreenLoad(lv_event_t * e);
void cb_clickedVoltAmmeterTB(lv_event_t * e);
void cb_voltammeterPower5V0ButtonChanged(lv_event_t * e);
void cb_voltammeterPower3V3ButtonChanged(lv_event_t * e);
void cb_voltammeterPowerPDButtonChanged(lv_event_t * e);
void cb_voltammeterPowerPDDropdownChanged(lv_event_t * e);
void cb_clickedVoltAmmeterToMenu(lv_event_t * e);
void cb_clickedUartMonitorToMenu(lv_event_t * e);
void cb_UartMonitorBaudValueChange(lv_event_t * e);
void cb_UartMonitorParityValueChange(lv_event_t * e);
void cb_PWMoutputScreenLoaded(lv_event_t * e);
void clicked_PWMoutput_to_menu(lv_event_t * e);
/**
 * @brief 根据十进制数字轮盘更新 PWM 周期和脉宽。
 *
 * @param e LVGL 数值变化事件。
 */
void cb_PWMRollerValueChanged(lv_event_t * e);
void cb_DACoutputScreenLoaded(lv_event_t * e);
void clicked_DAC_to_menu(lv_event_t * e);
/**
 * @brief 根据轮盘选项切换 DAC 输出波形。
 *
 * @param e LVGL 数值变化事件。
 */
void cb_DACWaveRollerChanged(lv_event_t * e);
/**
 * @brief 根据十进制数字轮盘更新 DAC 输出频率。
 *
 * @param e LVGL 数值变化事件。
 */
void cb_DACFrequencyRollerChanged(lv_event_t * e);

void cb_menutoAboutscreen(lv_event_t * e);
	
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
