// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "rtthread.h"
//#include "bsp_beep.h"
#include "power_control.h"
#include "screens.h"
#include "bsp_dac.h"

#define PWM_DEV_NAME "pwm1" /* PWM设备名称 */
#define PWM_DEV_CHANNEL 1 /* PWM通道 */

struct rt_device_pwm *pwm_dev; /* PWM设备句柄 */

extern lv_group_t *menu_group;
extern lv_group_t *daplink_group;
extern lv_group_t *file_explorer_group;
extern lv_group_t *offline_download_group;
extern lv_group_t *volt_ammeter_group_main;
extern lv_group_t *uart_monitor_group_main;
extern lv_group_t *pwm_output_group_main;
extern lv_group_t *dac_output_group_main;
extern lv_group_t * about_group_main;

extern lv_indev_t *indev;

extern char choose_device_path[LV_FILE_EXPLORER_PATH_MAX_LEN];
extern char choose_firmware_bin_path[LV_FILE_EXPLORER_PATH_MAX_LEN];

//代表当前选择的文件路径是返回到哪里，0表示未初始化，1表示返回到芯片型号选择，2表示返回到选择固件。
uint8_t current_path_return = 0;

void clicked_daplink_to_menu(lv_event_t * e)
{
	// Your code here
	lv_indev_set_group(indev, menu_group);
	current_screen_set(SCREEN_MENU);
}

void cb_clicked_menu_to_daplink(lv_event_t * e)
{
	// Your code here
	lv_indev_set_group(indev, daplink_group);
    current_screen_set(SCREEN_DAPLINK);
}

void cb_clicked_menu_to_file_explorer(lv_event_t * e)
{
	// Your code here
	
	current_path_return = 3;
	
	lv_indev_set_group(indev, file_explorer_group);
    current_screen_set(SCREEN_FILE_EXPLORER);
}

void cb_keydown_switch_list(lv_event_t * e)
{
	// Your code here
	lv_group_focus_next(file_explorer_group);
}


void cb_offlineDownloadToFileExplorerChooseDevice(lv_event_t * e)
{
	// Your code here
    current_path_return = 1;
    lv_indev_set_group(indev, file_explorer_group);
    current_screen_set(SCREEN_FILE_EXPLORER);
}

void cb_offlineDownloadtoFileExplorerChooseBin(lv_event_t * e)
{
	// Your code here
    current_path_return = 2;
    lv_indev_set_group(indev, file_explorer_group);
    current_screen_set(SCREEN_FILE_EXPLORER);
}

extern int8_t swd_download_update_flash_algo(char *_file_path);
extern int32_t swd_download_from_file(char *_file_path);


extern rt_sem_t offline_download_sem;

void cb_clickedStartDownload(lv_event_t * e)
{
	// Your code here
    rt_sem_release(offline_download_sem);
}

void clicked_OfflineDownload_to_menu(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, menu_group);
    current_screen_set(SCREEN_MENU);
}

void cb_clicked_menu_to_offline_download(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, offline_download_group);
    current_screen_set(SCREEN_OFFLINE_DOWNLOAD);
}

void cb_FileExplorerScreenLoad(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, file_explorer_group);
}

void cb_OfflineDownloadScreenLoad(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, offline_download_group);
    lv_label_set_text(ui_currentDevicePath, choose_device_path);
    lv_label_set_text(ui_currentBinPath, choose_firmware_bin_path);
}

void cb_daplinkPower5V0cCheckBoxValueChange(lv_event_t * e)
{
	// Your code here
    lv_obj_t *obj = lv_event_get_target(e);
    if (lv_obj_get_state(obj) & LV_STATE_CHECKED)
    {
        power_control_switch(POWER_5V0, POWER_STATE_ON);
    }
    else
    {
        power_control_switch(POWER_5V0, POWER_STATE_OFF);
    }
}

void cb_daplinkPower3V3cCheckBoxValueChange(lv_event_t * e)
{
	// Your code here
    lv_obj_t *obj = lv_event_get_target(e);
    if (lv_obj_get_state(obj) & LV_STATE_CHECKED)
    {
        power_control_switch(POWER_3V3, POWER_STATE_ON);
    }
    else
    {
        power_control_switch(POWER_3V3, POWER_STATE_OFF);
    }
}

void cb_daplinkPowerPDControlRollerValueChange(lv_event_t * e)
{
	// Your code here
    lv_obj_t *obj = lv_event_get_target(e);
    switch (lv_roller_get_selected(obj))
    {
        case 0:
            power_control_pd_sink_state(POWER_PD_5V);
            break;
        case 1:
            power_control_pd_sink_state(POWER_PD_9V);
            break;
        case 2:
            power_control_pd_sink_state(POWER_PD_12V);
            break;
        case 3:
            power_control_pd_sink_state(POWER_PD_15V);
            break;
        case 4:
            power_control_pd_sink_state(POWER_PD_20V);
            break;
        default:
            power_control_pd_sink_state(POWER_PD_5V);
            break;
    }
}

void cb_daplinkPowerPDOutputValueChange(lv_event_t * e)
{
	// Your code here
    lv_obj_t *obj = lv_event_get_target(e);
    if (lv_obj_get_state(obj) & LV_STATE_CHECKED)
    {
        power_control_switch(POWER_PD, POWER_STATE_ON);
    }
    else
    {
        power_control_switch(POWER_PD, POWER_STATE_OFF);
    }
}

void cb_VoltAmmeterScreenLoad(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, volt_ammeter_group_main);
    lv_tabview_set_act(ui_VATabview, 0, LV_ANIM_OFF);

    if (!is_3V3_power_on())
    {
        lv_obj_add_state(ui_VAOUTPUT3V3ENABLEB, LV_STATE_CHECKED);
        _ui_label_set_property(ui_VAOUTPUT3V3ENABLEL, _UI_LABEL_PROPERTY_TEXT, "3V3 DISABLE");
    }
    else
    {
        lv_obj_clear_state(ui_VAOUTPUT3V3ENABLEB, LV_STATE_CHECKED);
        _ui_label_set_property(ui_VAOUTPUT3V3ENABLEL, _UI_LABEL_PROPERTY_TEXT, "3V3 ENABLE");
    }
    if (!is_5V0_power_on())
    {
        lv_obj_add_state(ui_VAOUTPUT5V0ENABLEB, LV_STATE_CHECKED);
        _ui_label_set_property(ui_VAOUTPUT5V0ENABLEL, _UI_LABEL_PROPERTY_TEXT, "5V0 DISABLE");
    }
    else
    {
        lv_obj_clear_state(ui_VAOUTPUT5V0ENABLEB, LV_STATE_CHECKED);
        _ui_label_set_property(ui_VAOUTPUT5V0ENABLEL, _UI_LABEL_PROPERTY_TEXT, "5V0 ENABLE");
    }

    if(!is_PD_power_on())
    {
        lv_obj_add_state(ui_VAOUTPUTPDENABLEB, LV_STATE_CHECKED);
        _ui_label_set_property(ui_VAOUTPUTPDENABLEL, _UI_LABEL_PROPERTY_TEXT, "PD DISABLE");
    }
    else
    {
        lv_obj_clear_state(ui_VAOUTPUTPDENABLEB, LV_STATE_CHECKED);
        _ui_label_set_property(ui_VAOUTPUTPDENABLEL, _UI_LABEL_PROPERTY_TEXT, "PD ENABLE");
    }

    if(get_current_pd_voltage() == POWER_PD_5V)
    {
        lv_dropdown_set_selected(ui_VAPDOPTIONDropDown,0);
    }else if(get_current_pd_voltage() == POWER_PD_9V)
    {
        lv_dropdown_set_selected(ui_VAPDOPTIONDropDown,1);
    }else if(get_current_pd_voltage() == POWER_PD_12V)
    {
        lv_dropdown_set_selected(ui_VAPDOPTIONDropDown,2);
    }else if(get_current_pd_voltage() == POWER_PD_15V)
    {
        lv_dropdown_set_selected(ui_VAPDOPTIONDropDown,3);
    }else if(get_current_pd_voltage() == POWER_PD_20V)
    {
        lv_dropdown_set_selected(ui_VAPDOPTIONDropDown,4);
    }


}

void cb_clickedVoltAmmeterTB(lv_event_t *e)
{
    // Your code here
    lv_obj_t *obj = lv_event_get_target(e);
    lv_obj_t *_tabview = lv_obj_get_parent(obj);
    lv_tabview_t *_tabview_obj = (lv_tabview_t *)_tabview;


    if (_tabview_obj->tab_cur == 3)
    {
        // lv_indev_set_group(indev, volt_ammeter_group_set);
        lv_group_add_obj(volt_ammeter_group_main, ui_VAOUTPUT5V0ENABLEB);
        lv_group_add_obj(volt_ammeter_group_main, ui_VAOUTPUT3V3ENABLEB);
        lv_group_add_obj(volt_ammeter_group_main, ui_VAOUTPUTPDENABLEB);
        lv_group_add_obj(volt_ammeter_group_main, ui_VAPDOPTIONDropDown);
    }
    if(_tabview_obj->tab_cur == 0)
    {
        lv_indev_set_group(indev, volt_ammeter_group_main);
        lv_group_remove_obj(ui_VAOUTPUT5V0ENABLEB);
        lv_group_remove_obj(ui_VAOUTPUT3V3ENABLEB);
        lv_group_remove_obj(ui_VAOUTPUTPDENABLEB);
        lv_group_remove_obj(ui_VAPDOPTIONDropDown);
        lv_group_add_obj(volt_ammeter_group_main, ui_VAreturnHomeB);
    }
    if(_tabview_obj->tab_cur == 1)
    {
        lv_indev_set_group(indev, volt_ammeter_group_main);
        lv_group_remove_obj(ui_VAOUTPUT5V0ENABLEB);
        lv_group_remove_obj(ui_VAOUTPUT3V3ENABLEB);
        lv_group_remove_obj(ui_VAOUTPUTPDENABLEB);
        lv_group_remove_obj(ui_VAPDOPTIONDropDown);
        lv_group_add_obj(volt_ammeter_group_main, ui_VAreturnHomeB);
    }
    if(_tabview_obj->tab_cur == 2)
    {
        lv_indev_set_group(indev, volt_ammeter_group_main);
        lv_group_remove_obj(ui_VAOUTPUT5V0ENABLEB);
        lv_group_remove_obj(ui_VAOUTPUT3V3ENABLEB);
        lv_group_remove_obj(ui_VAOUTPUTPDENABLEB);
        lv_group_remove_obj(ui_VAPDOPTIONDropDown);
        lv_group_add_obj(volt_ammeter_group_main, ui_VAreturnHomeB);
    }
}

void cb_voltammeterPower5V0ButtonChanged(lv_event_t * e)
{
	// Your code here
    lv_obj_t *obj = lv_event_get_target(e);
    if (lv_obj_get_state(obj) & LV_STATE_CHECKED)
    {
        power_control_switch(POWER_5V0, POWER_STATE_OFF);
    }
    else
    {
        power_control_switch(POWER_5V0, POWER_STATE_ON);
    }
}

void cb_voltammeterPower3V3ButtonChanged(lv_event_t * e)
{
	// Your code here
    lv_obj_t *obj = lv_event_get_target(e);
    if (lv_obj_get_state(obj) & LV_STATE_CHECKED)
    {
        power_control_switch(POWER_3V3, POWER_STATE_OFF);
    }
    else
    {
        power_control_switch(POWER_3V3, POWER_STATE_ON);
    }
}

void cb_voltammeterPowerPDButtonChanged(lv_event_t * e)
{
	// Your code here
    lv_obj_t *obj = lv_event_get_target(e);
    if (lv_obj_get_state(obj) & LV_STATE_CHECKED)
    {
        power_control_switch(POWER_PD, POWER_STATE_OFF);
    }
    else
    {
        power_control_switch(POWER_PD, POWER_STATE_ON);
    }
}

void cb_voltammeterPowerPDDropdownChanged(lv_event_t * e)
{
	// Your code here
    lv_obj_t *obj = lv_event_get_target(e);
    switch (lv_dropdown_get_selected(obj))
    {
    case 0:
        power_control_pd_sink_state(POWER_PD_5V);
        break;
    case 1:
        power_control_pd_sink_state(POWER_PD_9V);
        break;
    case 2:
        power_control_pd_sink_state(POWER_PD_12V);
        break;
    case 3:
        power_control_pd_sink_state(POWER_PD_15V);
        break;
    case 4:
        power_control_pd_sink_state(POWER_PD_20V);
        break;
    default:
        power_control_pd_sink_state(POWER_PD_5V);
        break;
    }

}


void cb_screenToVoltAmmeter(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, volt_ammeter_group_main);
    current_screen_set(SCREEN_VOLT_AMMETER);
}

void cb_clickedVoltAmmeterToMenu(lv_event_t * e)
{
	// Your code here
	lv_indev_set_group(indev, menu_group);
    current_screen_set(SCREEN_MENU);
}

void cb_clickedAboutToMenu(lv_event_t * e)
{
	// Your code here
	lv_indev_set_group(indev, menu_group);
    current_screen_set(SCREEN_MENU);
}

void cb_loadedMenu(lv_event_t * e)
{
	// Your code here
	lv_indev_set_group(indev, menu_group);
	/* 查找设备 */
    pwm_dev = (struct rt_device_pwm *)rt_device_find(PWM_DEV_NAME);
}

#include "dap_main.h"
#include "usb_cdc.h"
extern struct cdc_line_coding g_cdc_lincoding;

void cb_screenToUartMonitor(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, uart_monitor_group_main);
    current_screen_set(SCREEN_UART_MONITOR);

    g_cdc_lincoding.bCharFormat = 0; //STB_1BIT
    g_cdc_lincoding.bDataBits = 8;
    g_cdc_lincoding.dwDTERate = 1200;
    g_cdc_lincoding.bParityType = 0;
    chry_dap_usb2uart_uart_config_callback(
        (struct cdc_line_coding *)&g_cdc_lincoding);
}

void cb_clickedUartMonitorToMenu(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, menu_group);
    current_screen_set(SCREEN_MENU);
}

void cb_UartMonitorBaudValueChange(lv_event_t * e)
{
	// Your code here
    lv_obj_t *obj = lv_event_get_target(e);

    g_cdc_lincoding.bCharFormat = 0; //STB_1BIT
    g_cdc_lincoding.bDataBits = 8;

    switch (lv_dropdown_get_selected(obj))
    {
    case 0:
        g_cdc_lincoding.dwDTERate = 1200;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 1:
        g_cdc_lincoding.dwDTERate = 2400;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 2:
        g_cdc_lincoding.dwDTERate = 4800;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 3:
        g_cdc_lincoding.dwDTERate = 9600;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 4:
        g_cdc_lincoding.dwDTERate = 19200;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 5:
        g_cdc_lincoding.dwDTERate = 34800;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 6:
        g_cdc_lincoding.dwDTERate = 57600;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 7:
        g_cdc_lincoding.dwDTERate = 74800;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 8:
        g_cdc_lincoding.dwDTERate = 115200;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 9:
        g_cdc_lincoding.dwDTERate = 230400;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 10:
        g_cdc_lincoding.dwDTERate = 460800;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 11:
        g_cdc_lincoding.dwDTERate = 500000;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 12:
        g_cdc_lincoding.dwDTERate = 576000;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 13:
        g_cdc_lincoding.dwDTERate = 1000000;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 14:
        g_cdc_lincoding.dwDTERate = 1500000;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 15:
        g_cdc_lincoding.dwDTERate = 2000000;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    default:
        g_cdc_lincoding.dwDTERate = 115200;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    }

}

void cb_UartMonitorParityValueChange(lv_event_t * e)
{
	// Your code here
    lv_obj_t *obj = lv_event_get_target(e);

    g_cdc_lincoding.bCharFormat = 0; //STB_1BIT
    g_cdc_lincoding.bDataBits = 8;

    switch (lv_dropdown_get_selected(obj))
    {
    case 0:
        g_cdc_lincoding.bParityType = 0;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 1:
        g_cdc_lincoding.bParityType = 2;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    case 2:
        g_cdc_lincoding.bParityType = 1;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    default:
        g_cdc_lincoding.bParityType = 0;
        chry_dap_usb2uart_uart_config_callback(
            (struct cdc_line_coding *)&g_cdc_lincoding);
        break;
    }
}

void cb_menutoPWMscreen(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, pwm_output_group_main);
    current_screen_set(SCREEN_PWM_OUTPUT);
}

void cb_menutoDACscreen(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, dac_output_group_main);
    current_screen_set(SCREEN_DAC_OUTPUT);
}

void cb_menutoAboutscreen(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, about_group_main);
    current_screen_set(SCREEN_ABOUT);
}

#include "stdio.h"
#include "drivers/rt_drv_pwm.h"

static rt_uint32_t pwm_rollers_get_value(lv_obj_t ** rollers)
{
    rt_uint32_t value = 0;
    uint8_t i;

    for(i = 0; i < UI_PWM_DIGIT_COUNT; i++)
    {
        value = value * 10U + lv_roller_get_selected(rollers[i]);
    }

    return value;
}

void cb_PWMRollerValueChanged(lv_event_t * e)
{
    rt_uint32_t period;
    rt_uint32_t pulse;

    (void)e;

    if (pwm_dev == RT_NULL)
    {
        rt_kprintf("get pwm device run failed! can't find %s device!!\n", PWM_DEV_NAME);
        return;
    }

    period = pwm_rollers_get_value(ui_PWMPeriodRollers);
    pulse = pwm_rollers_get_value(ui_PWMPulseRollers);
    if(period == 0U || pulse > period)
    {
        return;
    }

    rt_pwm_set(pwm_dev, PWM_DEV_CHANNEL, period, pulse);
}

void clicked_DAC_to_menu(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, menu_group);
    current_screen_set(SCREEN_MENU);
}

void clicked_PWMoutput_to_menu(lv_event_t * e)
{
	// Your code here
    lv_indev_set_group(indev, menu_group);
    current_screen_set(SCREEN_MENU);
}

void cb_PWMoutputScreenLoaded(lv_event_t * e)
{
	// Your code here
    rt_uint32_t period, pulse;
    period = 1000; /* 单位为纳秒ns */

    pulse = 500; /* PWM脉冲宽度值，单位为纳秒ns */

    //默认输出1Mhz的方波。

    if (pwm_dev == RT_NULL)
    {
        rt_kprintf("get pwm device run failed! can't find %s device!!\n", PWM_DEV_NAME);
    }
    /* 设置PWM周期和脉冲宽度默认值 */
    rt_pwm_set(pwm_dev, PWM_DEV_CHANNEL, period, pulse);
    /* 使能设备 */
    rt_pwm_enable(pwm_dev, PWM_DEV_CHANNEL);
}

void cb_DACoutputScreenLoaded(lv_event_t * e)
{
	// Your code here
}

void cb_DACWaveRollerChanged(lv_event_t * e)
{
    switch_waveform((WaveformType)lv_roller_get_selected(lv_event_get_target(e)));
}

void cb_DACFrequencyRollerChanged(lv_event_t * e)
{
    rt_uint32_t frequency = 0;
    uint8_t i;

    (void)e;
    for(i = 0; i < UI_DAC_FREQUENCY_DIGIT_COUNT; i++)
    {
        frequency = frequency * 10U + lv_roller_get_selected(ui_DACFrequencyRollers[i]);
    }

    if(frequency > 0U)
    {
        dac_timer_frequency_set(frequency);
    }
}

void cb_DAPLINKScreenLoad(lv_event_t * e)
{
	// Your code here
    if (is_3V3_power_on())
    {
        lv_obj_add_state(ui_Power3V3CheckBox, LV_STATE_CHECKED);
    }
    else
    {
        lv_obj_clear_state(ui_Power3V3CheckBox, LV_STATE_CHECKED);
    }
    if (is_5V0_power_on())
    {
        lv_obj_add_state(ui_Power5V0CheckBox, LV_STATE_CHECKED);
    }
    else
    {
        lv_obj_clear_state(ui_Power5V0CheckBox, LV_STATE_CHECKED);
    }

    if(is_PD_power_on())
    {
        lv_obj_add_state(ui_PDOutputEN, LV_STATE_CHECKED);
    }
    else
    {
        lv_obj_clear_state(ui_PDOutputEN, LV_STATE_CHECKED);
    }

    if(get_current_pd_voltage() == POWER_PD_5V)
    {
        lv_roller_set_selected(ui_PDControlRoller,0,LV_ANIM_ON);
    }else if(get_current_pd_voltage() == POWER_PD_9V)
    {
        lv_roller_set_selected(ui_PDControlRoller,1,LV_ANIM_ON);
    }else if(get_current_pd_voltage() == POWER_PD_12V)
    {
        lv_roller_set_selected(ui_PDControlRoller,2,LV_ANIM_ON);
    }else if(get_current_pd_voltage() == POWER_PD_15V)
    {
        lv_roller_set_selected(ui_PDControlRoller,3,LV_ANIM_ON);
    }else if(get_current_pd_voltage() == POWER_PD_20V)
    {
        lv_roller_set_selected(ui_PDControlRoller,4,LV_ANIM_ON);
    }

}
