import os
from building import * 

group = []

if not GetDepend('PKG_USING_OPTPARSE'):
    cwd = GetCurrentDir()
    src = Glob('*.c')
    inc = [cwd]
    group = DefineGroup('optparse', src, depend = [''], CPPPATH = inc)

    for d in os.listdir(cwd):
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            group += SConscript(os.path.join(d, 'SConscript'))

Return('group')
